### ISSUE TITLE
Style Guide: Ordering

### ISSUE THREAD

**Issue by msssk** [dojo/meta#107]
https://github.com/dojo/meta/blob/master/STYLE.md#ordering

Do we want to revisit this? While this has been specified in Dojo's style guide for years, I personally have not seen it put into practice.

Most commonly what I see is that methods are ordered in a way that someone new to the code, reading top to bottom, can get the best idea of what's going on. Alphabetic ordering does not serve this purpose.

For example, with Dijit widgets, methods are typically ordered with the lifecycle methods first, in order of execution. There may be more preferable approaches than alphabetic ordering, so it might be helpful to poll more people to see what they are actually doing, and decide if we want to strongly recommend people adhere to alphabetic ordering (and spell out what the benefits are), or if we want to revise our style guide recommendation.

**Comment by rishson** [comment]
@msssk I read the guide to mean 'alphabetic' within an items place in an order, but since functions need to be declared before use, then the flow will essentially be bottom up. We are trying to enforce this in Dojo 2. Is this issue to disagree with the coding standards as they currently stand, or to ask for clarification/enforcement?

**Comment by msssk** [comment]
The items I have issue with are for class properties and methods:

* ordered alphabetically, case-insensitively, ignoring leading underscores
    * leading underscore has been used (and continues?) to indicate non-public API properties. Across programming languages it is a common practice to group private, protected, and public members separately, and in the past (despite these guidelines having been in place for quite some time), we have followed the common practice of grouping public members separately from non-public members. I propose we update the guidelines to continue this practice.
* Class properties SHOULD be ordered alphabetically
    * As mentioned above, I have not seen this guideline adhered to much, and I'm not convinced it should be adhered to. It is more common that methods are ordered logically according to the module structure and functionality, for example, Dijit Widgets typically order lifecycle methods by order of execution. In the absence of any inherently logical ordering of methods, I'm in favor of alphabetic ordering, but I generally find it reasonable and useful to group related methods together and to order sequentially executed methods one after the other.

**Comment by dylans** [comment]
@msssk I think these suggestions are reasonable. I'm not sure if we have made much use of _ in Dojo 2 (I know that today we renamed render to __render__ to indicate it should never be overridden. :)

**Comment by agubler** [comment]
The style guide is largely redundant with the adoption of prettier for code style rules.
