### ISSUE TITLE
How to setup or use a dojo-2 package from git directly?

### ISSUE THREAD

**Issue by gbaumgart** [dojo/meta#109]
Hi, I am trying to setup and use any of the new dojo-2 packages, for instance dojo-compose. All my trials failed so far.

Here is my desired directory and file layout for now:

./my-dojo-1-package
./dojo-compose (installed via git, and did run `npm install` and `grunt` )
/test.ts
/tsconfig.json

whereby test.ts is requiring dojo-compose:

```ts
import compose from 'dojo-compose/compose';
const fooFactory = compose({
    foo: function () {
        console.log('foo');
    },
    bar: 'bar',
    qat: 1
});
```

Now there are 2 things I'd like to get working:  

1. compile it via command line: 

`tsc test.ts` (gives me test.ts(1,21): error TS2307: Cannot find module 'dojo-compose/compose')

so i can build a file-watcher in WebStorm

and 

2. my more desired setup: Using WebStorm's Typescript support (pointing to tsconfig.json and using the latest Typescript installed globally) : 

my tsconfig.json: 

```
{
  "version": "2.0.3",
  "compilerOptions": {
    "declaration": false,
    "module": "umd",
    "moduleResolution": "node", //tried others as well
    "noImplicitAny": true,
    "noImplicitThis": true,
    "outDir": "_build/",
    "removeComments": false,
    "sourceMap": true,
    "strictNullChecks": true,
    "rootDir": ".",
    "target": "es5",
    "baseUrl": ".",
    "paths": {                                            <----tried many things here too
       "dojo-compose/*": 
       [
        "dojo-compose/src/*" 
      ],
      "dojo-compose": "./dojo-compose/src/"
    }
  },
  "include": [
    "./compose/src/**/*.ts",
    "./compose/tests/**/*.ts",
    "./compose/typings/index.d.ts",
    "./test.ts"
  ]
}

```

Currently I get lots of errors from Webstorm: 

![image](https://cloud.githubusercontent.com/assets/1205100/20141103/27c07e76-a68f-11e6-95e3-b0397c3b41a3.png)

Before bugging you any longer: Is it possible at all to get Dojo-2 working that way ? (my other typescript projects are working just fine with WebStorm). Because after trying for many hours again, it seems rather not. 

You can close this here but as said, I am really interested to get any of the dojo-2 modules integrated, at worst I am willing to forget about Webstorm's rich TS support and it be ok to use command line tooling only. 

Dont you have a some document for contributors how to set this up? 

sorry for bothering
g

**Comment by gbaumgart** [comment]
who about I place all dojo-2 modules from git at one root, would it be easier or possible to use your packages then ? 

eg: 
/dojo2/compose
/dojo2/loader
/...

**Comment by agubler** [comment]
Hey @gbaumgart, 

To use dojo2 (including `dojo-compose`), may I suggest using the dojo CLI to create a new skeleton application that is ready to go.

To do this you need to install `dojo-cli` and `dojo-cli-create-app` globally

```bash
npm i dojo-cli -g
npm i dojo-cli-create-app -g
```

Then run the cli using `dojo create app --name myApp` that will generate a directory with all the current dojo 2 packages and dependencies, typings and a configured `tsconfig.json` file.

At this point you should be able ready to start to write code using dojo2! Once you have something that you would like to build you can use the dojo build command `dojo build` to produce a bundle in the `dist` directory or if you would like to serve and watch the `src` directory you can use `dojo build -w`.

This is a small dojo2 "Hello World!" example, you can add this to `src/main.ts` and perform a build to try it out.

```ts
import createWidget from 'dojo-widgets/createWidget';
import { createProjector } from 'dojo-widgets/projector';

const helloWorldWidget = createWidget({
	state: {
		label: 'Hello World!'
	}
});

const projector = createProjector({ root: document.body });
projector.append(helloWorldWidget);
projector.attach();
```

Hopefully this provides enough of a base to start to achieve your original goals plus enable all of the rich TS support available in Webstorm.

I hope that helps enable you to get started with dojo2 and welcome any feedback that you may have.

**Comment by gbaumgart** [comment]
so i did and it looks slightly better. 

i made some path mappings in my tsconfig:

```json
{
  "version": "2.0.3",
  "compilerOptions": {
    "declaration": false,
    "module": "umd",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "outDir": "_build/",
    "removeComments": false,
    "sourceMap": true,
    "strictNullChecks": true,
    "rootDir": ".",
    "target": "es5",
    "baseUrl": ".",
    "paths": {
      "dojo-compose/*": [
        "./dojo2/compose/src/*"
      ],
      "dojo-core/*": [
        "./dojo2/core/src/*"
      ],
      "dojo-shim/*": [
        "./dojo2/shim/src/*"
      ],
      "dojo-has/*": [
        "./dojo2/has/src/*"
      ],
      "dojo-loader/*": [
        "./dojo2/loader/src/*"
      ],
      "dojo-interfaces/*": [
        "./dojo2/interfaces/src/*"
      ]
    }
  },
  "include": [
    "./test.ts"
  ]
}

```

which gives me: 
mc007@mcdev:/PMaster/projects/x4mm/Code/client/src/lib$ tsc
dojo2/core/src/global.ts(6,18): error TS2304: Cannot find name 'global'.
dojo2/core/src/global.ts(8,10): error TS2304: Cannot find name 'global'.
dojo2/has/src/has.ts(54,18): error TS2304: Cannot find name 'global'.
dojo2/has/src/has.ts(56,10): error TS2304: Cannot find name 'global'.
dojo2/has/src/has.ts(227,13): error TS2304: Cannot find name 'process'.
dojo2/has/src/has.ts(227,37): error TS2304: Cannot find name 'process'.
dojo2/has/src/has.ts(227,57): error TS2304: Cannot find name 'process'.
dojo2/has/src/has.ts(228,10): error TS2304: Cannot find name 'process'.
dojo2/shim/src/Symbol.ts(7,14): error TS2304: Cannot find name 'SymbolConstructor'.
dojo2/shim/src/Symbol.ts(9,22): error TS2304: Cannot find name 'SymbolConstructor'.
dojo2/shim/src/Symbol.ts(45,27): error TS2304: Cannot find name 'Symbol'.

I had a look at your tscconfigs and it seems the typings/index.d.ts is missing everywhere. So i did run 
npm install ;  grunt ; 

Anyhow, after 3 hours toying, I am afraid about the worst case is going to happen with dojo2: 

- require lots of resources (2GB in total for all dojo-2 module)
- really really good hardware because tsc is pretty hungry
- awful slow (compiling a single file with one dojo2-require can last 5-10 secs)
- overly complicated
- really difficult or impossible to integrate your code base the usual way (needs npm install for every package).

I am even afraid that you locked in your own build-chain and its mandatory to run it so this will render standard IDEs own build-chains useless as well. 

your code looks great, just that you've locked it up in a heavy fortress and nobody can actually use or build on it.

thanks anyway, 

ps: what a pity, i was really waiting but from what i see is far from "good software"
g

**Comment by gbaumgart** [comment]
@agubler: 

thanks a lot, but now. I want it really directly integrated from git with no npm or what ever in between except in my own parent application.

**Comment by agubler** [comment]
@gbaumgart Is there any particular reason why you are looking to use `git` clones rather than install the packaged dependency from `npm`?

**Comment by gbaumgart** [comment]
just to make it clear: I want to use/modify dojo2 sources as before: git clone dojo-2 package(s) somewhere, then coding....no npm or whatsoever except it can be done from global. as max. a file watcher to re-compile changed files...

I am probably too much old-fashion but its really a pain to see all that new code build on clouds ;-)

**Comment by gbaumgart** [comment]
@agubler , ah just saw your last post: yes, for a number of reasons: 

- using the sources directly in the parent project, being able to fork and patch it myself
- no footprint
- being able to integrate it in my own tool-chain (mostly classy globals)
- being able to zip the project and run it somewhere else without internet
- simplicity
- being independent from wasteful npm
- internet can't be a requirement

**Comment by kitsonk** [comment]
> ps: what a pity, i was really waiting but from what i see is far from "good software"

Sorry to be frank, but I don't think that is an honest assessment and sort of hurts.  Feedback is great and welcomed.  We are trying to understand your use case and assumptions.  As you are aware, JavaScript tooling is hugely complex topic these days and we have been focused on getting the functional code working well.  We aren't even in a beta yet, because we know we aren't ready.  You have to realise that there is a whole team of human being who you likely inadvertently just "called their baby ugly".

Our aim was to provide an out of the box toolchain, and you have found some obvious gaps with that, which we are working on fixing.

As far as how to integrate into a larger tool chain, one that doesn't fit the "out of the box" one, we want to make the possible and as relatively as painless as possible.  You picked up a pre-beta set of software, less than 24 hours ago and ran into some issue, which we were trying to help you with.  Frustrated you called our hard work not good software. 😢

**Comment by gbaumgart** [comment]
okokokok, come on Kitsonk, I said its great code. You and the rest of the team always delivered good code, so good that I dropped C++ and then spent the last 8-9 years with Dojo only on a full time base. I am delighted!

But please understand, if you lock it up entirely and ditch it to many toolchains needed to be installed on a package base (not like gcc,g++) and you force users and their desired applications to be connected to fast internet and expensive hardware, then yes: not good software as a whole. Really wasn't a offense at all. I just noticed at the first sight. 

I am sure you can get this done as good software has to be, small, fast, and easy to integrate with no superior npm's dictatorship and the need for expensive internet, as we had in dojo-1 : no pain at all.

Look: I am doing primarily authoring software, since very long. The requirements of educational software are not that obvious, especially for people from the rich western world where resources are "no problem". 

For instance, in my world: users (teachers) need to be able to use this codebase from within an offline application to teach their students. Then a student goes usually with the outcome home and wants to proceed on his own, more likely having no internet. So the teacher gives them the runtime, the editor and nodejs with some globals like tsc on a zip drive. I honestly a little surprised that Dojo-2 somehow throws this good and golden requirements over board...

I already made tremendous efforts to support NodeJS based code in this scenarios and just to tell you: 80% can be deleted after npm install. I can only accept git as package source because its the only option, something you can setup in LAN and so you are free to ignore a proprietary and commercial service like npm :-)

ok, sorry in case i was a dickhead. I am going to wait another 2-3 months again and try harder next time. 

but yes, I want dojo-2 sources as the primary DSL in all my apps. 
g

**Comment by gbaumgart** [comment]
if its of any interest, i started recently a npm module with simulates somehow [git sub modules](https://github.com/control-freak-ide/git-module). the idea is to get around npm at any cost, and always being able to switch and between release/debug versions and of course: making packages finally friendly for forking, patching and overlays, etc....also in a way you can control the final directory layout in projects by some variables and data coming from package.json or command line:

```json
"modules":[
    {
      "name":"server-template",
      "options":{
        "repository": "https://github.com/gbaumgart/xcf-servers.git",
        "recursive":true,
        "directory":"server-template"
      },
      "clone": {
        "post": {
          "command": "git submodule foreach \"git checkout master\""
        }
      }
    }
  ]
```

I tested the idea (like svn externals, just better) in some projects and I am pretty happy about already. I basically want to add dojo-2 modules.

**Comment by gbaumgart** [comment]
I promise you not bother again, but please tell me how to set it up only :-) you already said its symlinks but that's far from ideal.

**Comment by gbaumgart** [comment]
never mind. I got something working but after toying a while it turns out indeed as complex monster. 

Way to big to handle for me as single developer; also outsourcing to other devs will be to expensive for me. back to square one, easy and real source code ;-)
