### ISSUE TITLE
Update Copyright notices/LICENSE

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#110]
Now that the JSFoundation is fully a thing, we should migrate all the copyright notices, where applicable, to JS Foundation.  Also, it seems to be the common thing to emit years as part of a copyright notice.

**Comment by dylans** [comment]
Need the same updates for LICENSE files as well.

**Comment by rishson** [comment]
All beta 1 repos now have PR to bring license details up to date, so I'll remove the beta-blocker label when they are all merged.

**Comment by rishson** [comment]
There are still some repos with invalid license information, but all beta 1 repos as now updated.

**Comment by rishson** [comment]
Check final Dojo 2 repos:
- [ ] test-extras
- [ ] dgrid
- [ ] streams
- [ ] app
- [ ] parser
- [ ] crypto
- [ ] dataviz
