### ISSUE TITLE
Suggestion: "Standalone" development build

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#112]
While it wouldn't be a preferred way of developing, there might be a use case that as we approach beta, we could generate a "standalone" Dojo 2 development environment for Windows 10, MacOS and Linux.  That environment would include in the bundle:

- A version of Visual Studio Code
  - Configured with Chrome debugger and node integrations, and potentially any dev plugins we will want/develop for Dojo 2
- The published versions of main packages of Dojo 2
- Appropriate development dependencies
- An install of `dojo` CLI

Ideally too, `dojo` CLI would be able to framework a new application without need of internet connectivity.  We had previously discussed a set of meta data for CLI that would be located "live" in some location, but could be bundled in the single downloadable.

This would give a developer assessing Dojo 2 an even simpler path to get started then `npm install dojo-cli` and would enable those with limited connectivity to the internet to be able to develop on Dojo 2.

**Comment by rahmanha** [comment]
This will be a great environment for development with Dojo. A self contained tool with debugging system will also be great to understand interaction between different modules. By now Visual Studio Code also grained huge popularity. Excellent choices, indeed.

Now we are eagerly waiting for 2.0 beta. When that will be released?

**Comment by dylans** [comment]
> Now we are eagerly waiting for 2.0 beta. When that will be released?

We're currently aiming for mid-late Q1 2017 for a full Dojo 2 beta, though we won't call it all beta until we're very happy with all the things.

dgrid and dataviz will be post-beta, but prior to the final 2.0 release.

We expect to have a fairly long beta period (3-6 months) as we'll need the time for documentation and demos (as well as getting dgrid and dataviz in order).

**Comment by sebilasse** [comment]
I would like to draw attention to http://fractal.build - it is made by the nice people from clearleft UK and there is this issue to move forwards : https://github.com/frctl/fractal/issues/197

**Comment by kitsonk** [comment]
The plan at the moment is to provide a workbench as an Electron app that would be based on the [dojo/web-editor](https://github.com/dojo/web-editor).
