### ISSUE TITLE
Symbols/Iterators and removing Symbol shim

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#113]
`dojo-shim` introduces a custom typing called `symbol-shim`, which is then required by any packages that consume `dojo-shim`.  This is not necessary if we were to configure our `lib` in the `tsconfig.json` and likely would be a better/safer way to handle this in the long term (making it easier to migrate to ES6/ES2015 emit).

The `tsconfig.json` would need to be amended to add the following `"lib"` to:

```json
{
	"compilerOptions": {
		"lib": [
			"dom",
			"es5",
			"es2015.iterable",
			"es2015.symbol",
			"es2015.symbol.wellknown"
		]
	}
}
```

At that point we would be able to remove the `"symbol-shim"` property from the `typings.json`.

**Comment by agubler** [comment]
Should we update the non active repositories as part of this issue? Or address them when work is started again?

**Comment by agubler** [comment]
- [ ] [dojo-has](https://github.com/dojo/has)
- [ ] [dojo-shim](https://github.com/dojo/shim)
- [ ] [dojo-core](https://github.com/dojo/core)
- [ ] [dojo-compose](https://github.com/dojo/compose)
- [ ] [dojo-widgets](https://github.com/dojo/widgets)
- [ ] [dojo-actions](https://github.com/dojo/actions)
- [ ] [dojo-routing](https://github.com/dojo/routing)
- [ ] [dojo-dom](https://github.com/dojo/dom)
- [ ] [dojo-examples](https://github.com/dojo/examples)
- [ ] [dojo-stores](https://github.com/dojo/stores)
- [ ] [dojo-i18n](https://github.com/dojo/i18n)

**Comment by agubler** [comment]
I have updated dojo/actions

**Comment by dylans** [comment]
> Should we update the non active repositories as part of this issue?

Yes, in case someone tries to use them or wants to get involved, etc.

**Comment by agubler** [comment]
> Yes, in case someone tries to use them or wants to get involved, etc.

I have done `actions` and will do `dom`, but I fear `app` is not actually even possible

**Comment by agubler** [comment]
Okay all merged apart from `@dojo/app` that will be essentially impossible, closing.
