### ISSUE TITLE
Implement a documentation generator

### ISSUE THREAD

**Issue by rishson** [dojo/meta#116]
Refs: #115 
Create `html` documentation from a parsed api (produced by our doc parser).
Features:

- [x] should layout the documentation to be readable
- [x] should style the documentation to be readable
- [ ] should create dir structure that mirrors the documentation structure
- [ ] should create links between definitions

**Comment by rishson** [comment]
Styling WIP being developed [here](http://codepen.io/rishson/pen/eBRGRY?editors=1100).

**Comment by dylans** [comment]
Closing in favor of working on TypeDoc to improve it.
