### ISSUE TITLE
Migrate to Intern ~3.4.1

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#117]
Migrating to Intern ~3.4.1 requires that we address the issue of dropping out the `dojo2-dev` typings from the `typings.json` and having the packages fully converted over to `@types`.

Refs #113 and #62

**Comment by agubler** [comment]
I think we might actually be completely converted for all our modules...

**Comment by dylans** [comment]
I think core still points to 3.3.2, and maybe a few others...

**Comment by agubler** [comment]
oh sure, Okay i'll do that then.

**Comment by kitsonk** [comment]
This is essentially done.
