### ISSUE TITLE
Remove bower.json from projects

### ISSUE THREAD

**Issue by matt-gadd** [dojo/meta#118]
We don't publish nor have we tested support for bower right now, so we should remove the bower.json from our template and projects until there is a time we decide to support.

**Comment by matt-gadd** [comment]
- [ ] [dojo-has](https://github.com/dojo/has)
- [ ] [dojo-shim](https://github.com/dojo/shim)
- [ ] [dojo-core](https://github.com/dojo/core)
- [ ] [dojo-compose](https://github.com/dojo/compose)
- [ ] [dojo-widgets](https://github.com/dojo/widgets)
- [ ] [dojo-actions](https://github.com/dojo/actions)
- [ ] [dojo-routing](https://github.com/dojo/routing)
- [ ] [dojo-cli](https://github.com/dojo/cli)
- [ ] [dojo-cli-build](https://github.com/dojo/cli-build)
- [ ] [dojo-cli-create-app](https://github.com/dojo/cli-create-app)
- [ ] [dojo-loader](https://github.com/dojo/loader)
- [ ] [dojo-dom](https://github.com/dojo/dom)
- [ ] [dojo-examples](https://github.com/dojo/examples)
- [ ] [dojo-interfaces](https://github.com/dojo/interfaces)
- [ ] [dojo-stores](https://github.com/dojo/stores)
- [ ] [dojo-i18n](https://github.com/dojo/i18n)
- [ ] [dojo-cli-css-typings](https://github.com/dojo/cli-css-typings)

**Comment by matt-gadd** [comment]
We are also coupled to node resolution with typescript, and we use `@types` which is only on `npm` so we're likely never to support bower.

**Comment by edhager** [comment]
dojo/widgets did not have a bower.json file.

**Comment by edhager** [comment]
dojo/cli did not have a bower.json file.

**Comment by edhager** [comment]
dojo/cli-create-app did not have a bower.json file.

**Comment by edhager** [comment]
dojo/examples did not have a bower.json file.

**Comment by edhager** [comment]
All of the pull requests are in place.  Below is a checklist to track the pull requests.  Note, not all Dojo 2 repos had bower.json files.

- [ ] [dojo-has](https://github.com/dojo/has/pull/32)
- [ ] [dojo-shim](https://github.com/dojo/shim/pull/65)
- [ ] [dojo-core](https://github.com/dojo/core/pull/265)
- [ ] [dojo-compose](https://github.com/dojo/compose/pull/115)
- [ ] [dojo-actions](https://github.com/dojo/actions/pull/29)
- [ ] [dojo-routing](https://github.com/dojo/routing/pull/66)
- [ ] [dojo-cli-build](https://github.com/dojo/cli-build/pull/39)
- [ ] [dojo-loader](https://github.com/dojo/loader/pull/99)
- [ ] [dojo-dom](https://github.com/dojo/dom/pull/63)
- [ ] [dojo-interfaces](https://github.com/dojo/interfaces/pull/58)
- [ ] [dojo-stores](https://github.com/dojo/stores/pull/97)
- [ ] [dojo-i18n](https://github.com/dojo/i18n/pull/44)
- [ ] [dojo-cli-css-typings](https://github.com/dojo/cli-css-typings/pull/9)
- [ ] [dojo2-package-template](https://github.com/dojo/dojo2-package-template/pull/78)
