### ISSUE TITLE
Will Dojo 2 support HTML partials?

### ISSUE THREAD

**Issue by vansimke** [dojo/meta#127]
Many web applications rely on the server to render HTML fragments to illustrate the result of an AJAX call. Since Dojo 2 uses a virtual DOM, this could lead to a situation in which the server has to offload work to the client that might lead to inefficiency or compromise security by forcing data to be shared that shouldn't be. 
This issue is intended to raise the question of if Dojo 2 will support HTML partials and, if so, how.

**Comment by kitsonk** [comment]
This is really covered under SSR.  This specific feature may or may not be relevant for the bigger SSR feature set, so closing in favour of #181
