### ISSUE TITLE
Move to the @dojo namespace

### ISSUE THREAD

**Issue by matt-gadd** [dojo/meta#129]
Prior to beta, we'd like to move all of our packages over to the `@dojo` namespace on npm (for example `dojo-core/Evented` becomes `@dojo/core/Evented`. To do this we can either leverage https://github.com/dojo/grunt-dojo2/pull/65, or we can actually just rename all of our imports to be `@dojo/package`. The second is more preferable in the long run as the source will match the output.

The list to change:

- [x] [dojo-has](https://github.com/dojo/has)
- [x] [dojo-shim](https://github.com/dojo/shim)
- [x] [dojo-streams](https://github.com/dojo/streams)
- [x] [dojo-core](https://github.com/dojo/core)
- [x] [dojo-compose](https://github.com/dojo/compose)
- [x] [dojo-widgets](https://github.com/dojo/widgets)
- [x] [dojo-routing](https://github.com/dojo/routing)
- [x] [dojo-cli](https://github.com/dojo/cli)
- [x] [dojo-cli-build](https://github.com/dojo/cli-build)
- [x] [dojo-cli-create-app](https://github.com/dojo/cli-create-app)
- [x] [dojo-loader](https://github.com/dojo/loader)
- [x] [dojo-examples](https://github.com/dojo/examples)
- [x] [dojo-interfaces](https://github.com/dojo/interfaces)
- [x] [dojo-stores](https://github.com/dojo/stores)
- [x] [dojo-i18n](https://github.com/dojo/i18n)

**Comment by dylans** [comment]
For consistency, should we do this for all 26 or so repos, even the deprecated or less active ones? e.g. dataviz, parser, crypto?

**Comment by matt-gadd** [comment]
@dylans if we plan to go to a `beta` for them then yes.

**Comment by agubler** [comment]
Should we move to `dependencies` over `peerDependencies` in the same process?

**Comment by agubler** [comment]
Personally think it would be nice to reset all the versions to `alpha.1` as part of this so that when we move to beta for dojo2, all the packages start together on `beta.1`, thoughts?

**Comment by agubler** [comment]
We are not looking to move `grunt-dojo2` as part of this issue, that package will remain outside the dojo namespace as it is 100% internal to assist with the dojo2 development, testing, publishing lifecycle(s).

**Comment by agubler** [comment]
Have thought about and talked through with @matt-gadd about the reseting of versions and decided it is not feasible due to many reasons not least the fact that the tags already exist.

**Comment by agubler** [comment]
The dependency order that the packages need publishing is:

1. dojo/loader
2. dojo/has
3. dojo/shim
4. dojo/interfaces
5. dojo/core
6. dojo/streams
7. dojo/compose
8. dojo/i18n
9. dojo/stores
10. dojo/widgets
11. dojo/routing
12. dojo/cli
13. dojo/cli-build
14. dojo/cli-create-app

**Comment by rishson** [comment]
All done!
