### ISSUE TITLE
Create new repo `intern-helpers` and move common test functionality into it

### ISSUE THREAD

**Issue by rishson** [dojo/meta#131]
We seem to just be copying things like `mockModule` around in repo tests. We should create a repo for generic test helper functionality and then reference from the tests.
This repo should include (but is not limited to):

- `mockModule`
- `testUtils` that includes things like `returnImmediate` and `reporter`.

**Comment by kitsonk** [comment]
Created now at: https://travis-ci.org/dojo/intern-helper

Also refs dojo/examples#197

**Comment by dylans** [comment]
This was addressed with the creation of https://github.com/dojo/test-extras/ .
