### ISSUE TITLE
dojo-core/load and alignment for ES import()

### ISSUE THREAD

**Issue by dylans** [dojo/meta#133]
@kitsonk commented on [Tue Oct 04 2016](https://github.com/dojo/core/issues/202)

There is a Stage 2 proposal for [`import()`](https://github.com/domenic/proposal-import-function) which would essentially be the same as our `load`.

We should potentially consider aligning to that proposal and potentially migrating it to `dojo-shim`.

---

@dylans commented on [Thu Jan 12 2017](https://github.com/dojo/core/issues/202#issuecomment-272243234)

Now at stage 3, we should decide what to do with this.

**Comment by dylans** [comment]
Per @matt-gadd : I don't believe we can implement imports here in dojo/core. Mainly due to us needing a contextual require to work with relative paths for AMD. The imports topic is probably a larger discussion in dojo/meta and dojo/loader.

**Comment by kitsonk** [comment]
Closed in favour of dojo/shim#81.
