### ISSUE TITLE
Fix the npm version badges

### ISSUE THREAD

**Issue by agubler** [dojo/meta#135]
With the move to @dojo namespaced packages the badges for npm version on the readme have been broken.

Updated links can be generated here https://badge.fury.io/for/js

The list to check 

- [x] [dojo-has](https://github.com/dojo/has)
- [x] [dojo-shim](https://github.com/dojo/shim)
- [x] [dojo-streams](https://github.com/dojo/streams)
- [x] [dojo-core](https://github.com/dojo/core)
- [x] [dojo-compose](https://github.com/dojo/compose)
- [x] [dojo-widgets](https://github.com/dojo/widgets)
- [x] [dojo-routing](https://github.com/dojo/routing)
- [x] [dojo-cli](https://github.com/dojo/cli)
- [x] [dojo-cli-build](https://github.com/dojo/cli-build)
- [x] [dojo-cli-create-app](https://github.com/dojo/cli-create-app)
- [x] [dojo-loader](https://github.com/dojo/loader)
- [x] [dojo-interfaces](https://github.com/dojo/interfaces)
- [x] [dojo-stores](https://github.com/dojo/stores)
- [x] [dojo-i18n](https://github.com/dojo/i18n)

**Comment by rishson** [comment]
Refs #129

**Comment by rishson** [comment]
Done!
