### ISSUE TITLE
Remove node engines from package.json

### ISSUE THREAD

**Issue by matt-gadd** [dojo/meta#136]
I'm not even sure why we have this set. There is no runtime dependency on a node version, and the only reason its there is to satisfy `grunt-dojo2` (which won't be used by our consumers). This provides unnecessary friction for consumers. 

If someone feels strongly enough that developers using `grunt-dojo2` aren't capable of having a recent node version (and our documentation doesn't lead them down that path), then we should just down emit `grunt-dojo2`

https://github.com/dojo/dojo2-package-template/blob/master/package.json#L6

**Comment by matt-gadd** [comment]
To update, the reason we have it set is due to the fact we have a grunt task that installs peer deps on installation (which kind of defeats the purpose of having peer deps in the first place). So we should potentially down emit to es5 for grunt-dojo2 to fix this properly.

**Comment by dylans** [comment]
@agubler I thought it had been handled for all repos... I guess not! :)

**Comment by agubler** [comment]
I think I've just got the last two outstanding ones has and core.

**Comment by rishson** [comment]
I'll check and update `has` and `core`

**Comment by rishson** [comment]
Will raise a PR to have min version 3 of `npm` in all `package.json`.
