### ISSUE TITLE
Touch, Pointer and 3D touch events

### ISSUE THREAD

**Issue by dylans** [dojo/meta#141]
With native pointer events landing recently in Chrome 55 (and other browsers already), need to make sure we're covered for pointer events.

Also received a request today asking what our plan is for supporting 3D touch events. https://github.com/freinbichler/3d-touch and https://pressurejs.com/ are a few implementations, so it seems possible.

In general, let's look at our strategy around event handlers that are not universally supported and what we should do (for example, we could consider https://github.com/jquery/PEP for pointer events which has been our answer to date)...

**Comment by dylans** [comment]
I think knowing what we're doing around touch and pointer events is something we need to finalize before beta 1, so adding the beta-blocker label.

**Comment by matt-gadd** [comment]
closing this a pointer events support is now added. separate issue for 3D touch here: https://github.com/dojo/meta/issues/155
