### ISSUE TITLE
Event patterns

### ISSUE THREAD

**Issue by dylans** [dojo/meta#142]
Now that much of widget-core has stabilized, and now that we're starting on dgrid alpha, there are some patterns that we probably need to decide on around events.

For example, in a dgrid cell, we might switch a cell from readonly to an editable field via a focus event, or a click event, or a touch event ( I'll defer to #141 for touch event discussion).

So, in the case of having potentially multiple event types that might conflict with each other or have overlapping behavior, what is the right pattern to follow? Perhaps a custom event type that encapsulates all of the relevant event types. Or a single event handler for multiple event types that then normalizes things? What if two events happen consecutively, and you really want an action to happen for one of them, but not both, etc.?

I'm sure there are better ways to manage this that my stream of consciousness... but it would be helpful to define the pattern(s) to follow so that we have a relatively consistent approach across widgets.

**Comment by agubler** [comment]
@dylans is this issue still relevant?

**Comment by dylans** [comment]
I think we've covered it as much as we're going to, so closing it out.
