### ISSUE TITLE
State injection containers

### ISSUE THREAD

**Issue by matt-gadd** [dojo/meta#146]
We're now at a point where the widgeting system is nearly complete and for building components the property system suffices for passing of state and callbacks.

In larger apps this is a cumbersome and coupled way to get state and callbacks/actions down the tree of widgets when working with an application state store.

In react-redux the concept of a`Container` act as a kind of virtual widget which allow you to side load application state and actions. We have had similar concepts in the past with `externalState` that do similar but not quite as complete in functionality.

As part of the issue we should probably look at whether there is a place for an `actions` like mechanism (dojo/actions) or whether simple functions suffice.

**Comment by rishson** [comment]
Issue moved to [dojo/widget-core #440](https://github.com/dojo/widget-core/issues/440) via [**ZenHub**](https://www.zenhub.com/)
