### ISSUE TITLE
Make the new PR template consistent across packages

### ISSUE THREAD

**Issue by dylans** [dojo/meta#147]
Currently there's a lack of consistency for the new PR template (and new issue template) across our various packages.

Let's decide what we want from each and update them.

Also there are a few differences in workflow... for example, some package (but not most) automatically set the pipeline for things. Some packages (dojo2-package-template) auto-block a merge until there's a review but most packages do not, etc.

**Comment by agubler** [comment]
I agree we should normalise the issue and pull request template across all packages.

As for the requirement of a review, we cannot have that set on any packages that we release, as unfortunately it also blocks pushes to master.

**Comment by agubler** [comment]
Going to normalise all templates to match the current package template - https://github.com/dojo/dojo2-package-template/tree/master/.github

**Comment by agubler** [comment]
PRs raised for all out of date repos.

**Comment by agubler** [comment]
All PRs merged.
