### ISSUE TITLE
Migration to TypeScript 2.3

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#153]
This is a master issue to address migration to [TypeScript 2.3 features](https://github.com/Microsoft/TypeScript/wiki/Roadmap#23-may-2017) that we care about:

- Migrate [to `--strict` flag](https://github.com/Microsoft/TypeScript/pull/14486).
- Adopt [`this` typing](https://github.com/Microsoft/TypeScript/pull/14141).
- Implement generators ([now supported on ES3/ES5](https://github.com/Microsoft/TypeScript/issues/1564)).
- Implement [generic type defaults](https://github.com/Microsoft/TypeScript/pull/13487).

There is also basic plugin support for the language services in 2.3, I don't know if there is anything that would benefit from writing a plugin.

**Comment by kitsonk** [comment]
[TypeScript 2.3 is Released](https://blogs.msdn.microsoft.com/typescript/2017/04/27/announcing-typescript-2-3/)

**Comment by dylans** [comment]
Given that we're on 2.4 now, I'm going to close this epic. Any remaining 2.3.x tickets I'm seeing are moving to 2.4.
