### ISSUE TITLE
General run list to verify before beta1 

### ISSUE THREAD

**Issue by matt-gadd** [dojo/meta#157]
This is a general list of things we should validate for beta1, to make sure generally everything is working holistically. Please feel free to edit and add.

* can install `@dojo/cli` globally
* can run `dojo create app`
    * produces expected file structure
* can run `dojo build`
    * output works in browser
    * correct sourcemaps back to original css and ts
    * .d.ts files for css should be automatically created/updated
    * check build report generated in dist
    * check sanity of built sizes/included modules
* can run `dojo build -w`
     * server runs, output works in browser
     * modifying a module updates in browser
     * .d.ts files for css should be automatically created/updated
* can run `dojo test`
     * unit test results should output
* can create custom element using `dojo build --element`
    * The outputted custom element is useable
* can import a widget from `dojo/widgets`
* can build and run `dojo/examples/todo-mvc`
* can build and run `dojo/examples/todo-mvc-kitchensink`

**Comment by agubler** [comment]
I've run through a few of these recently:

* Install `@dojo/cli` globally
* Run `dojo create app` with the expected project structure, that is buildable with `dojo build` and `dojo build -w` and the unit tests run with `dojo test`. Also tested that for the latest changes in PR https://github.com/dojo/cli-create-app/pull/57
* Able to run `dojo build`, this is executed for `dojo/examples/todo-mvc` and `dojo/examples/todo-mvc-kitchensink` on CI. Also tested against applications created by `dojo create app` and [`le-grid`](https://github.com/agubler/le-grid/)
* Verified that sourcemaps back to the the original css and ts (this is viewable on [todo-mvc](https://dojo.github.io/examples/todo-mvc/) and [todo-mvc-kitchensink](https://dojo.github.io/examples/todo-mvc-kitchensink/))
* Verified that typings are created for css using both `dojo build` and `dojo build -w`
* Current example app bundle sizes
  * `todo-mvc`: 114kb (36.1kb gzipped)
  * `todo-mvc-kitchensink`: 286kb (93.9kb gzipped)
* Verified that running `dojo build -w` runs the server on the specified port (default 9999) and is runnable in the browser (chrome).
* Verified that `dojo test` does run unit tests and provide an output, `dojo test -a` runs functional tests also. There is an outstanding issue for coverage that needs to be addressed.

Hopefully that covers some of the tasks that @matt-gadd has listed above.

**Comment by rishson** [comment]
Verified:
- can import a widget from dojo/widgets
- can build and run dojo/examples/todo-mvc
 - can build and run dojo/examples/todo-mvc-kitchensink
