### ISSUE TITLE
The API supporting the first Dojo2 widgets

### ISSUE THREAD

**Issue by pdfernhout** [dojo/meta#16]
[What](url) API layer should be underneath the first Dojo2 widgets? 

There are at least two approaches to providing a base API for creating extensible a11y i18n Dojo2 widgets (assuming a vdom is used). One is a HyperScript-like API that is close to the DOM, and the other is a (presumably new) API that hides the DOM. Pros and cons are below.

### HyperScript API

One approach is to use a [HyperScript-ish API](https://lhorie.github.io/mithril/mithril.html) with a [chosen vdom](https://github.com/dojo/meta/issues/11#issuecomment-176790243) that is close to the DOM to construct some a11y and i18n widgets (with at the very least an equivalent for each core Dijit1 widget). Those widgets could then be composed into more complex widgets as needed, and so programmers could mostly avoid learning about the DOM if they were willing to work just within what was possible by that approach. Programmers who were comfortable with the DOM could use HyperScript directly to make new widgets by working close to the DOM if they needed to.

Pros:
* We would be building on proven technologies that have good performance.
* Good components on top of a HyperScript API [might hide the DOM in a "good enough" way](https://dzone.com/articles/the-dom-sucks-and-it-should-become-a-second-class) for most use cases.
* A Dojo2 GUI could always be made to perform as well as possible by dropping down to coding at the HyperScript API level.
* Existing widgets implemented using HyperScript (like for Mithril or virtual-dom) could be readily adapted to Dojo2 projects.
* The Dijit2 widget set might have immediate uptake and contributions by existing users of the chosen vdom (who then might also get interested in the rest of Dojo2 if they liked the new Dijit2 widgets). 
* Any of the core maintainers of vdom projects like Mithril, Mercury/virtual-dom, or Bobril would likely be pleased to see a big set of widgets using their vdom, especially a11y ones with i18n support, and so they might be more inclined to be cooperative if small changes were needed to the vdom or API in relation to Dojo2.
* Any future experiments towards a better-than-DOM API could eventually be built on HyperScript at a little extra performance cost.
* We could make support functions to help create a11y and i18n widgets using composable functions instead of subclassing.
* Working at the DOM level may get easier over time regarding the need to hide browser inconsistencies, given Microsoft has [ended support](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) for IE versions before IE11 on current Windows platforms, browsers are often now autoupdating, and older hardware will eventually be upgraded.
* Most JavaScript developers probably already know the basics of the DOM and CSS, and there is much explanatory material already available on the web on using the DOM and CSS to achieve all sorts of effects.
* We could start building Dijit2 as soon as an initial vdom was decided on, and thus we could start creating pre-alpha Dojo2 apps sooner which would drive further design discussions about Dojo2 to explore other issues @kitsonk has raised (like immutability).

Cons:
* The DOM is [often said to be not a great API](http://programmers.stackexchange.com/questions/147451/whats-so-bad-about-the-dom).
* Depending on the vdom choice, an existing component building API in, say, Mithril might not be ideal from a Dojo2 perspective and require an extra wrapping layer
* Other functionality of the framework might overlap Dojo2 and be hard to hide if using the vdom's existing HyperScript layer.
* Developers working at the HyperScript API level might create widgets that are not a11y or ignore separation of concerns.

### DOM-hiding API

A different approach is to choose or create some low-level API that hides the DOM entirely (and perhaps CSS too), and then build Dojo2 widgets on that new API. Dojo2 developers would be expected to always either be building a webapp on top of that new API or to be composing components previously built on that new API. No DOM knowledge would be expected among Dojo2 developers.

Pros:
* The new API (or perhaps chosen API if such exists) would presumably be a better designed API than DOM.
* The new API might be easier to learn and remember compared to learning DOM.
* The new API could be designed to help enforce separation of concerns somehow.
* The new API could be designed to enforce a11y or i18n somehow.
* A new API could hide current browser inconsistencies at a low level and also provide a way to deal with future browser incompatibilities.
* The new API (if well designed) might even be portable to other GUI toolkits like Swing, QT, or TK (or might just be exactly the same API such as Swing's).

Cons:
* Performance may be slower depending on the degree of mismatch between the new abstraction and the DOM.
* Any new API typically has little documentation at first, and what documentation there is may get rapidly out-of-date.
* Trying to design some better-than-DOM API for the low level might take a long time -- delaying the development of Dojo2 widgets and webapps.
* Any new API has a long uphill climb for adoption.
* The new widgets would likely be harder to integrate with an existing vdom API and so might have little community support at first.
* Any new abstraction over the DOM and/or CSS would likely still "leak" and so still require webapp developers to learn the DOM and CSS. In such a situation, the new API could run the risk of being seen as just "in the way" of desired DOM and CSS interactions.
* DOM knowledge that Dojo2 developers did have would not be useful and might even be misleading in using the new API (e.g. Dijit introduced addChild to substitute for DOM appendChild, yet removeChild is the same between Dijit and DOM).
* It likely would be impossible in practice to build a HyperScript API on top of a non-DOM-oriented API, foreclosing that option (without going around the new API somehow).
* Essentially, a substantial new API to replace the DOM and CSS is a research project with an uncertain outcome.

### Discussion

This issue is a summary of Issue #15 to better promote discussion as recommend by @dylans. That issue itself was a spinoff of issue #11. 

Because [Dijit had contributed so much to the success of the Dojo toolkit according to Dylan's 2010 FOSDEM talk](https://www.youtube.com/watch?v=giIMjRWqbgo&feature=youtu.be&t=1034), I feel this Dojo2 widget issue should be a high priority one to resolve and get moving forward on.

I am biased on this based on [previous experience migrating from Dijit1 to Mithril](http://www.pdfernhout.net/on-moving-to-mithril-and-typescript-for-narrafirma.html) and enjoying working with Mithril. With a HyperScript approach used in a Mithril way, I feel there is a relatively straightforward path, where in a few weeks of full-time work, we might have the beginnings of a set of Dojo2 widget components good enough to start critiquing and improving and using in pre-alpha projects as test cases to drive further design discussions.

What do other people think? Are there more pros and cons I should add to be fairer? Are there other options worth listing besides those two?

**Comment by pdfernhout** [comment]
Another possible APi approach is to adopt the React API exactly as-is. Several other vdom libraries have done that, as noted in the list of vdoms in issue #11. 

Pros:
* cooperate with component builders in the React community
* existing React users may find this easy to pick up

Cons:
* I've read a few comments suggesting that API is suboptimal in design (but I need more specifics) 
* React seems to be fundamentally slower in practice than Mithril and some other vdoms because everything is a component requiring an extra layer of abstraction
* Facebook might potentially claim a patent or copyright violation in relation to the API it created (unlikely, but conceivable)

Not being a React user, I can't fully fill these pros and cons out fully.

**Comment by kitsonk** [comment]
This is going to be addressed by the Widget Proposal/Prototype.
