### ISSUE TITLE
Update linting and style guide

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#164]
There are many improvements and added capabilities in TSLint.  We should revisit our default `tslint.json` against the [currently supported rules](https://palantir.github.io/tslint/rules/) and take advantage of linting features that are sometimes implicit in what we have been doing.

There is also then an opportunity to re-visit our style guide and be more explicit about some things.

Related to dojo/grunt-dojo2#127

**Comment by agubler** [comment]
All the tslint configurations have been updated and now most repositories use prettier for code automatic code styling rules.
