### ISSUE TITLE
LICENSE files

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#165]
Not all of our license files have been updated to the [JS Foundation](https://github.com/dojo/grunt-dojo2/blob/64c49b56fa00afa49729f17bc0edc5e5475ec9d2/LICENSE) and some have them still mention the [Dojo Foundation in the 3rd clause](https://github.com/dojo/cli-test-intern/blob/0befa99df7a5ca4b39f3716425eb20c7dfa380fe/LICENSE#L15).

We should double check all the license files.

**Comment by rishson** [comment]
Looks like `LICENSE` for:

- [ ] compose
- [ ] examples
- [ ] gruntDojo2

**Comment by rishson** [comment]
All LICENSE updated.
