### ISSUE TITLE
Update Dojo url in package.json

### ISSUE THREAD

**Issue by dylans** [dojo/meta#166]
Once dojo.io is live, update url in various package.json repos to dojo.io so that it links to that on npm for future releases.

**Comment by rishson** [comment]
Update repo url and `package.json` url to `dojo.io` in:

- [ ] [dojo-app](https://github.com/dojo/app)
- [ ] [dojo-actions](https://github.com/dojo/actions)
- [ ] [dojo-cli](https://github.com/dojo/cli)
- [ ] [dojo-cli-build](https://github.com/dojo/cli-build)
- [ ] [dojo-cli-build-webpack](https://github.com/dojo/cli-create-app)
- [ ] [dojo-cli-create-app](https://github.com/dojo/cli-create-app)
- [ ] [dojo-cli-test-intern](https://github.com/dojo/cli-test-intern)
- [ ] [dojo-compose](https://github.com/dojo/compose)
- [ ] [dojo-core](https://github.com/dojo/core)
- [ ] [dojo-crypto](https://github.com/dojo/crypto)
- [ ] [dojo-dataviz](https://github.com/dojo/dataviz)
- [ ] [dojo-dgrid](https://github.com/dojo/dgrid)
- [ ] [dojo-dom](https://github.com/dojo/dom)
- [ ] [dojo-examples](https://github.com/dojo/examples)
- [ ] [dojo-has](https://github.com/dojo/has)
- [ ] [dojo-i18n](https://github.com/dojo/i18n)
- [ ] [dojo-interfaces](https://github.com/dojo/interfaces)
- [ ] [dojo-loader](https://github.com/dojo/loader)
- [ ] [dojo-routing](https://github.com/dojo/routing)
- [ ] [dojo-shim](https://github.com/dojo/shim)
- [ ] [dojo-stores](https://github.com/dojo/stores)
- [ ] [dojo-streams](https://github.com/dojo/streams)
- [ ] [dojo-test-extras](https://github.com/dojo/test-extras)
- [ ] [dojo-widgets](https://github.com/dojo/widgets)
- [ ] [dojo-widget-core](https://github.com/dojo/widget-core)

**Comment by rishson** [comment]
Should land dojo/grunt-dojo2#135 before doing this work.

**Comment by rishson** [comment]
@agubler if we wanted to make this less painful, then would we alter `grunt-dojo2` '` `package` to check the `package.json` 's `homepage` and autocorrect to `dojo.io` or would it be better to do [this](dojo/grunt-dojo2#135), or some other solution?

**Comment by agubler** [comment]
@rishson It certainly is possible to enhance the release task to correct `package.json` meta data on release.

We could also potentially create a task that can auto update `package.json` meta independently of the release.

**Comment by rishson** [comment]
@agubler yup and I have a PR ready to go for enhancing the release task. Would you prefer a generic 'alter metadata' task, e.g. [here](https://github.com/dojo/grunt-dojo2/issues/135), or a hardcoded `update url` check to the `release` task?

**Comment by rishson** [comment]
Most repos will now be updated by #183

**Comment by kitsonk** [comment]
Let's try to action this and close it out.  @eheasley if Dylan doesn't have the time, we should assign it to others.

**Comment by kitsonk** [comment]
Again, please action this.

**Comment by edhager** [comment]
Skipping dojo/examples because it does not have a package.json file.

**Comment by edhager** [comment]
PRs have been created for the unchecked (for now) repos above.

**Comment by edhager** [comment]
All PRs have been landed.
