### ISSUE TITLE
Clarity between Dojo 1.x and 2.x packages

### ISSUE THREAD

**Issue by dylans** [dojo/meta#174]
- [x] Review all dojo packages to verify that they state clearly if they are part of Dojo 1.x or 2.0+
- [ ] Update org description to be clear about 2.0+ vs. 1.x
- [x] Update URL in org to dojo.io (verify we're ready for that)
- [ ] Do something about dojo/dojo2 package as that is completely confusing now (would require updates to Intern and perhaps others)

**Comment by rishson** [comment]
Re: `dojo/dojo2`:
- [ ] Update README, repo tags and repo description
- [ ] make sure that intern can move off this package
- [ ] unpublish
- [ ] remove repo

**Comment by rishson** [comment]
I plan on changing all the repo descriptions for `dojo1` repos to:

Dojo 1 - xx

e.g.

for `dojo/dojo`:

`Dojo 1 - the Dojo toolkit core library.`

For dojo 2 repos, I plan on ensuring all the repo desciptions are in the form:

🚀 Dojo 2 - xx

e.g. for `dojo/widgets`

🚀 Dojo 2 - UI components

**Comment by agubler** [comment]
Just to note that with the loaderless-intern work that Jason has been doing, `intern` has already moved away from the `dojo` package published from `dojo/dojo2`.

**Comment by rishson** [comment]
@dylans can you 👍 or 👎 the comment above about the repo descriptions before I go through and change pls?

**Comment by dylans** [comment]
> Just to note that with the loaderless-intern work that Jason has been doing, intern has already moved away from the dojo package published from dojo/dojo2.

Yes, the challenge is all of the versions of Intern 2.x and 3.x that will break if the repo is just going. So we probably need to go back and publish a version of every Intern 2.x and 3.x with a dependency on whatever the new name is.

Also as Kit pointed out, we may still need a repo call dojo2 to not break our current single gitter channel for Dojo 2.

**Comment by agubler** [comment]
@dylan does it require the GitHub repo?

**Comment by agubler** [comment]
And for the Gitter stuff, `meta` should probably be `dojo2`....

**Comment by dylans** [comment]
> @dylan does it require the GitHub repo?

it can probably just require the npm tag, we'll need to verify with @jason0x43 

> And for the Gitter stuff, meta should probably be dojo2

Probably, but meta is such a fun self-troll over meta problems.

**Comment by agubler** [comment]
Yup I can't see a reason why it would need the repo. As the dependency is actually `dojo` but published from `dojo/dojo2` repo on the `2.0.0-Alpha.*` versions

**Comment by agubler** [comment]
I'm not sure what harm the repo is actually causing? It doesn't show up on an npm package search (grunt-dojo2 is actually the first result for dojo2) and it displays a big deprecated warning on the result returned from google.

**Comment by dylans** [comment]
Because it makes it look like Dojo 2 is deprecated (for people that are tl;dr

**Comment by agubler** [comment]
Agreed. In that case my previous comment still stands that we don't need the repo for intern.

**Comment by dylans** [comment]
> Agreed. In that case my previous comment still stands that we don't need the repo for intern.

I assume any incremental bug fix releases to old versions of Intern can continue to rely on the already published version. If that's the case, then yes, I agree, though it should still live somewhere in case someone needs it for something later (hopefully never).

**Comment by agubler** [comment]
We could just rename the repo as it has no bearing on the actual package it publishes to npm 😄 Maybe `dojo-intern`

**Comment by rishson** [comment]
OK - so I think gitter should just move to our org `dojo` (you can have org rooms as well as repo rooms).
I think we should rename `dojo/dojo2` to `dojo/dojo-intern` and mark as '(internal use)'.

I have been through all repos and done the following:

- All descriptions start with 'Dojo 1 -' or '🚀 Dojo 2 -'
- All deprecated repos now have this tag
- All 'proposed' repos now have this tag
- All 'internal use' repose now have this suffix in their description.

**Comment by dylans** [comment]
Ok, because npm just pulls in data from the readme and package.json, we may want to make changes there as well for the repos? I noticed the dojo/loader readme also uses dojo2 rather than Dojo 2. Also after 2.0 is released, we should probably change to 2+.

Moving gitter to the org seems fine to me.

**Comment by rishson** [comment]
Refs #166

**Comment by kitsonk** [comment]
That other actions are their for this.  It is unclear.  If there are other actions, maybe we should close this and break them out as separate issues?

**Comment by kitsonk** [comment]
No feedback for 3 months, closing.  Any actions should be open as new issues.
