### ISSUE TITLE
FirefoxDriver throws an error when trying to click on a disabled element

### ISSUE THREAD

**Issue by lzhoucs** [dojo/meta#182]
I found this issue on browserstack. When trying to click on a disabled element, FirefoxDriver throws an `Element is not enabled` error whereas it is working in all other platforms. Error detail as follows:
```
InvalidElementState: [POST https://(redacted)@hub.browserstack.com:443/wd/hub/session/4b17298c88dd376c8f4d12120b8ec5f4155e72b1/element/21/click / {}] Element is not enabled
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '199-7-164-14', ip: '199.7.164.14', os.name: 'windows', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Windows\proxy\rust_mozprofile.tkixdA3S9QsG, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=6.1, moz:processID=4908.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
```
I couldn't find a related issue reported externally, so I put it here for tracking purpose as per Dylan.

One of the workaround is to add an error callback before proceeding with other operations:
```.ts
// suppose we are in the context of the disabled element
command
	.click()
	.then(undefined, (err: Error) => {
		// the error callback is needed only in FireFox with FirefoxDriver since it throws an 'Element is not enabled' error when clicking on an disabled element
	})
// other operation in the chain can be proceeded.

```

**Comment by kitsonk** [comment]
@jason0x43 @bryanforbes any thoughts on this... feels like an Intern issue.

**Comment by jason0x43** [comment]
The current version of geckodriver [incorrectly throws an error when trying to click a disabled element](https://github.com/mozilla/geckodriver/issues/615). From the bugzilla issues linked from the GH issue, it looks like they're working on a fix (switching to a WebDriver-compliant interaction check), but it hasn't made it into geckodriver yet.

**Comment by jason0x43** [comment]
We could update leadfoot with a new feature test to handle this case. In the current spec the only action that should explicitly return an invalid element state error is trying to clear the contents of a non-interactable editable/resettable element.

**Comment by kitsonk** [comment]
@jason0x43 this doesn't really seem like a Dojo 2 thing.  Should we open something on Intern Leadfoot or is this effectively handled now?

**Comment by jason0x43** [comment]
This is not specifically handled by Leadfoot at the moment. There is an open issue https://github.com/theintern/leadfoot/issues/119. I haven't checked in a while; that issue is still open, but is the problem still occurring?

**Comment by kitsonk** [comment]
I have no idea.  We don't have any issues with our functional tests at the moment.  If it occurs again, we will work to ensure we better isolate the issue.
