### ISSUE TITLE
Move packages to use BrowserStack

### ISSUE THREAD

**Issue by agubler** [dojo/meta#186]
Convert remaining Dojo 2 packages that use saucelabs to browserstack.

**Comment by kitsonk** [comment]
Anything left?  If so we should either list in this issue or raises issues in the other repos.

**Comment by dylans** [comment]
Did a quick review of packages that either still use SL or do not have the more recent BrowserStack credentials:

[] @dojo/app
[] @dojo/cli
[] @dojo/cli-build-webpack
[] @dojo/cli-create-app
[] @dojo/cli-export-project
[] @dojo/cli-test-intern
[] @dojo/interfaces
[] @dojo/i18n
[] @dojo/streams

And of course the inactive/deprecated packages:
[] dojo/actions
[] dojo/crypto
[] dojo/dataviz
[] dojo/compose
[] dojo/dom
[] dojo/parser

**Comment by kitsonk** [comment]
The CLI packages and Interfaces don't get tested on BrowserStack (because they don't run in a browser).  We should remove the credentials from them, so as to not confuse.

**Comment by kitsonk** [comment]
This is just dross we should focus on clearing out.

**Comment by edhager** [comment]
dojo/i18n was converted during the upgrade to Intern 4 (dojo/i18n#94).

dojo/interfaces is not tested remotely.

I was told that dojo/app was being rewritten and should be converted to Intern 4 and BrowserStack.  We can create an "Upgrade to Intern 4" ticket in dojo/app if desired.

From @dylans's list, dojo/streams has not been addressed.  It has not been converted to Intern 4 and its CI build is still using SauceLabs.  This is also true of the deprecated repos.

**Comment by kitsonk** [comment]
Streams is just "neglected" at the moment until we have a compelling use case to dust it off and maintain it.  We should just create an issue about upgrading the testing to Intern 4 and ensuring it is moved to browser stack, but we would schedule it for a future bit and not tie it to this issue or the intern upgrade Epic.
