### ISSUE TITLE
Implement Hacker News readers as Progressive Web Apps

### ISSUE THREAD

**Issue by agubler** [dojo/meta#187]
HNPWA is a successor to the traditional todo-mvc application, for frameworks to demonstrate implementations of web concepts.

Dojo 2 should look to implement the HNPWA example application to the requirements/specification provided [here](https://github.com/tastejs/hacker-news-pwas).

A list of all the existing framework implementations can be found at https://hnpwa.com/.

**Comment by kitsonk** [comment]
We essentially did this and learned a fair amount from the process... I am going to close this issue and if there is more we need to do later on, we either re-open or tackle it under other issues.

**Comment by agubler** [comment]
@kitsonk I've submitted a dojo 2 implementation (still in a PR) of the hacker news PWA [here](https://github.com/agubler/dojo-2-hn).
