### ISSUE TITLE
Style Guide: Checking defined for callbacks

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#191]
**Syle Guide**

When writing code, especially event handlers/callback in widgets, there is a need to check to see if the callback is defined.  We have been using two forms generally, we should agree to and use one.

The first form is a `if` block like:

```ts
if (onClick) {
  onClick();
}
```

The other form is a binary check:

```ts
onClick && onClick();
```

While the former is more formal, and we do tend to side towards clarity, allowing minification to optimise these sorts of blocks (which does convert it to `onClick && onClick()`).  On the other hand, the latter pattern is fairly common in general code and its intent is clear because of how common it is.

**Comment by agubler** [comment]
We use prettier for code formatting now
