### ISSUE TITLE
Targeting of Builds

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#20]
_Broken off from #18._

How do we deal with ES6+ only distributions effectively?

From a problem statement, it is essentially an end user should be able to build an optimized build that targets a "modern browser" and effectively elides unnecessary code while still maintain the same API so the user does not have to rewrite their code.  We should also provide them with the appropriate tooling to be able to also provide code that can be elided when targeting a "modern browser".  We may also want to include a pre-built "modern" version in our distributions to make it easy for someone to _grab-and-go_.

There are at least three keys to this puzzle:
- We need a better understanding of how we are going to elide code with the `has` API.
- We need [Conditional Decorators](https://github.com/Microsoft/TypeScript/issues/3538) which is targeted for TypeScript 2.1.
- We need [Granular Targeting](https://github.com/Microsoft/TypeScript/issues/4692) which doesn't have an item yet on the TypeScript roadmap but it is committed (I suspect it is an omission, likely 2.1).

Are there any other thoughts/considerations/etc?

**Comment by dylans** [comment]
Conditional Decorators do not seem to be on the roadmap yet.

Granular targeting (or at least the things it was to cover) does seem to be supported in 2.1.

**Comment by kitsonk** [comment]
We are delivering build optimization in dojo/cli-build#172, there isn't much more that is actionable from this at the moment.  It gives effective eliding of built in functionality at build time.
