### ISSUE TITLE
Discoverability of development commands

### ISSUE THREAD

**Issue by jason0x43** [dojo/meta#203]
The current @dojo build system is `grunt` based and has a large number of commands. This makes discovering how to perform standard dev tasks, such as how to build or test a project, a more complex process than it could be. For example, running running `grunt --help` in @dojo/core currently generates:

```
                           clean  Clean files and folders. *
                            copy  Copy files. *
                          intern  Custom multi task. *
                   remapIstanbul  Custom multi task. *
                          rename  Custom multi task. *
                         replace  General purpose text replacement for grunt.
                                  Allows you to replace text in files using
                                  strings, regexs or functions. *
                          tslint  A linter for TypeScript. *
                         typings  A Grunt plugin for typings *
                              ts  Compile TypeScript files *
                  uploadCoverage  Custom task.
                  peerDepInstall  Custom task.
                            repl  Bootstrap dojo-loader and start a Node.js
                                  REPL
                             run  Bootstrap dojo-loader and run the given
                                  --main
               can-publish-check  check whether author can publish
             repo-is-clean-check  check whether the repo is clean
                 release-publish  publish the package to npm
 release-version-pre-release-tag  auto version based on pre release tag
        release-version-specific  set the version manually
            post-release-version  update the version post release
            release-publish-flat  publish the flat package
                         release  release
                           _link  Custom task.
                            link  link
                   fixSourceMaps  Custom task.
                         postcss  Process CSS files. *
                         dojo-ts  Custom task.
                         typedoc  Custom task.
                            test  Custom task.
                             dev  Alias for "clean:typings", "typings:dev",
                                  "tslint", "clean:dev",
                                  "copy:staticDefinitionFiles-dev",
                                  "dojo-ts:dev", "copy:staticTestFiles" tasks.
                            dist  Alias for "clean:typings", "typings:dist",
                                  "tslint", "clean:dist",
                                  "copy:staticDefinitionFiles-dist",
                                  "dojo-ts:dist", "fixSourceMaps" tasks.
                        dist_esm  Alias for "dojo-ts:esm" task.
                             doc  Alias for "clean:typings", "typings:dev",
                                  "typedoc", "clean:typedoc", "clean:ghpages"
                                  tasks.
                         default  Alias for "clean", "dev" tasks.
```

A developer is likely only interested a few of these tasks, like 'dev', 'doc', and 'clean'. However, there's nothing to indicate which are the top-level tasks, and which are internal. 

While each [project README](https://github.com/dojo/core#installation) describes how to build that project, and the [build system itself](https://github.com/dojo/grunt-dojo2#grunt-dojo2) has a lengthy README, there is utility in a developer being able to rely on ecosystem-standard conventions, or being able to easily discover how to perform basic tasks. For example, a developer may forget an infrequently used command, such as how to build a test version of a package. Rather than having to go back to the README, the build system itself should allow such a command to be discovered.

One possibility is to use npm scripts (aliases defined in the "scripts" property in a project's package.json file). Many JS projects now use npm scripts with simple, task-focused names, such as "build", "lint", or "clean". These may be implemented using grunt, custom scripts, or simply shell commands. They key point is that the public interface is focused and is described in a standard location.

Grunt doesn't make this super easy, since there still isn't a straightforward way to [hide internal tasks](https://github.com/gruntjs/grunt/issues/741) from the help list. However, the main build tasks could still be made more discoverable. For example, the top level tasks could have descriptions like:

```
 dev *Build a development version of the project
dist *Build a distributable version of the project
 doc *Build the project's API documentation
```

**Comment by kitsonk** [comment]
Issue moved to [dojo/grunt-dojo2 #156](https://github.com/dojo/grunt-dojo2/issues/156) via [**ZenHub**](https://www.zenhub.com/)
