### ISSUE TITLE
Managing prerelease versions

### ISSUE THREAD

**Issue by jason0x43** [dojo/meta#204]
Currently, the peer dependencies of `@dojo` packages point to dist tags like 'next' or 'beta2'. This can cause invalid "missing peer dependency" warnings to be emitted during package installation for projects that depend on `@dojo` packages, effectively breaking the peer dependency mechanism (which is intended to warn users of peer dependencies that are _actually_ missing). Using tags in this way also obfuscates the real dependencies of a package and removes one of the core guarantees provided by the npm registry (that a version _can't_ change).

The `@dojo` packages should be able to use pre-release version ranges rather than dist tags to describe related groups of packages. Npm's semver library will compare all dot-separated components of a prerelease tag, and numeric components will be compared numerically. This allows npm to semantically compare a version like '2.0.0-beta.3.0.1' to a range like '>=2.0.0-beta.3.0.0 <2.0.0-beta.3.1.0'.

Using semantically comparable prerelease tags should allow the same flexibility the `@dojo` packages current get with dist tags, while making actual dependency versions more apparent and future proof (and avoiding spurious warnings).

**Comment by kitsonk** [comment]
I believe this is effectively resolved by using versions `0.#.#` but continuing to use our dist tags.
