### ISSUE TITLE
Upgrade to Intern 4.1.0

### ISSUE THREAD

**Issue by bryanforbes** [dojo/meta#211]
- [x] [`dojo/cli`](https://github.com/dojo/cli)
- [x] [`dojo/cli-build`](https://github.com/dojo/cli-build)
- [x] [`dojo/cli-create-app`](https://github.com/dojo/cli-create-app)
- [x] [`dojo/cli-create-widget`](https://github.com/dojo/cli-create-widget)
- [x] [`dojo/cli-export-project`](https://github.com/dojo/cli-export-project)
- [x] [`dojo/cli-test-intern`](https://github.com/dojo/cli-test-intern)
- [x] [`dojo/core`](https://github.com/dojo/core)
- [x] [`dojo/has`](https://github.com/dojo/has)
- [x] [`dojo/i18n`](https://github.com/dojo/i18n)
- [x] [`dojo/interfaces`](https://github.com/dojo/interfaces)
- [x] [`dojo/interop`](https://github.com/dojo/interop)
- [x] [`dojo/loader`](https://github.com/dojo/loader)
- [x] [`dojo/routing`](https://github.com/dojo/routing)
- [x] [`dojo/shim`](https://github.com/dojo/shim)
- [x] [`dojo/stores`](https://github.com/dojo/stores)
- [x] [`dojo/streams`](https://github.com/dojo/streams)
- [x] [`dojo/widget-core`](https://github.com/dojo/widget-core)
- [x] [`dojo/widgets`](https://github.com/dojo/widgets)
- [x] [`dojo/dojo2-package-template`](https://github.com/dojo/dojo2-package-template)
- [x] [`dojo/grunt-dojo2`](https://github.com/dojo/grunt-dojo2)
- [x] [`dojo/grunt-dojo2-extras`](https://github.com/dojo/grunt-dojo2-extras)
- [x] [`dojo/test-extras`](https://github.com/dojo/test-extras)
- [x] [`dojo/web-editor`](https://github.com/dojo/web-editor)
- [x] [`dojo/webpack-contrib`](https://github.com/dojo/webpack-contrib)

**Comment by agubler** [comment]
Going to remove examples and dgrid from this meta issue and open specific issues on each repo so this can be closed out.

**Comment by agubler** [comment]
Closing as all packages have been updated.
