### ISSUE TITLE
Update specification documents

### ISSUE THREAD

**Issue by dylans** [dojo/meta#22]
I think our various specification documents are getting a bit stale. It would be nice to keep them in sync with our current thinking where possible.

**Comment by kitsonk** [comment]
At what point do the specifications transition to a living standard?
Keeping the documents in sync with built packages are a folly that adds
little to no value. Once the package is established, auto generated
documentation should take over.

**Comment by dylans** [comment]
Auto-generated documentation is of course course, but what it often lacks or loses is the why of the decisions we made and what our motivations were. I think we still want something that documents our architectural and philosophical decisions, which the specs do a fairly good job of explaining.

**Comment by kitsonk** [comment]
I still argue that those are transient.  Several of those decisions weren't captured in those documents when they were fresh.  I think generally they are a point in time, often to "start" something but they begin to die as soon as you start cutting code.

Architectural decisions are "here is a problem" and then a "here is the solution we chose".  After there is actual code, those should be dealt with in issues and resolved.

Architectural documents don't help explain your solution to other people either, that takes a different type of documentation all together.

So if they don't assist the team building the code (maintain a document and cutting code at the same is a challenge at best) and they don't help explain what you are doing to the outside world once you have a repository of code...  Point issues (like this one) a format of issue tracking is far more effective for reasoning why a decision was made.

**Comment by dylans** [comment]
Spec docs will be removed when we get around to writing tutorials and documentation, so closing this out.
