### ISSUE TITLE
Document release process and expectations

### ISSUE THREAD

**Issue by dylans** [dojo/meta#222]
Document how we release for the following use cases:

* End developer (what to expect with each major and minor release, e.g. how version numbers will be kept in sync for x.y, but may vary for x.y.z)
* Contributor (steps to follow to create a release, tools/bots, etc., if we haven't already documented this somewhere)

**Comment by agubler** [comment]
@dylans do you want to take a first stab at this as per what your vision for the release process will be?

**Comment by dylans** [comment]
After discussing this more, we have decided that it makes sense to have major versions synced. e.g. all packages for 2.x will start with a 2.0 release. Packages may be out of sync with 2.x and 2.x.y from a numbering perspective.

The only significant challenge I see here is that any 2.x package should be known to work with any other 2.x package, which may introduce testing challenges. But I think we can resolve that through package.json information. Hopefully any non-bug breaking changes would just force us to 3.x, at which point every package would get a new major version number.
