### ISSUE TITLE
Missing 'tslib' when TypeScript should use external helpers

### ISSUE THREAD

**Issue by mgroenhoff** [dojo/meta#226]
Some packages have `"importHelpers": true` present in their `tsconfig.json` files but have no dependency on `tslib` or have `tslib` as a development dependency.

I have checked packages listed at [Packages](https://github.com/dojo/meta#packages) and found the following:

* [`dojo/cli`](https://github.com/dojo/cli) https://github.com/dojo/cli/pull/175 missing dependency `tslib`
* [`dojo/cli-build-app`](https://github.com/dojo/cli-build-app) https://github.com/dojo/cli-build-app/pull/1 missing dependency `tslib`
* [`dojo/cli-build-webpack`](https://github.com/dojo/cli-build-webpack) https://github.com/dojo/cli-build-webpack/pull/237 missing dependency `tslib`
* [`dojo/cli-create-app`](https://github.com/dojo/cli-create-app) https://github.com/dojo/cli-create-app/pull/120 extraneous dependency  `tslib` so either remove it or add `"importHelpers": true`
* [`dojo/cli-export-project`](https://github.com/dojo/cli-export-project) https://github.com/dojo/cli-export-project/pull/14 extraneous dependency  `tslib` so either remove it or add `"importHelpers": true`
* [`dojo/core`](https://github.com/dojo/core) https://github.com/dojo/core/pull/367 move `tslib` from `devDependencies` to `dependencies`
* [`dojo/interop`](https://github.com/dojo/interop) https://github.com/dojo/interop/pull/18 missing dependency `tslib`
* [`dojo/i18n`](https://github.com/dojo/i18n) https://github.com/dojo/i18n/pull/103 missing dependency `tslib`
* [`dojo/routing`](https://github.com/dojo/routing) https://github.com/dojo/routing/pull/116 missing dependency `tslib`
* [`dojo/stores`](https://github.com/dojo/stores) https://github.com/dojo/stores/pull/140 missing dependency `tslib`
* [`dojo/streams`](https://github.com/dojo/streams) https://github.com/dojo/streams/pull/15 missing dependency `tslib`
* [`dojo/widget-core`](https://github.com/dojo/widget-core) https://github.com/dojo/widget-core/pull/752 missing dependency `tslib`
* [`dojo/widgets`](https://github.com/dojo/widgets) https://github.com/dojo/widgets/pull/369 missing dependency `tslib`

You probably also want to use the same version range for `tslib` in all packages.

**Comment by matt-gadd** [comment]
@mgroenhoff thanks a lot for checking this, it looks like pretty much all of the current dojo packages. there is also another org wide change in packages for another issue: https://github.com/dojo/meta/issues/223. we can probably ship both as part of `beta5` this week

**Comment by matt-gadd** [comment]
for initial tracking:
- [x] [`dojo/core`](https://github.com/dojo/core)
- [ ] [`dojo/examples`](https://github.com/dojo/examples)
- [ ] [`dojo/i18n`](https://github.com/dojo/i18n)
- [ ] [`dojo/interop`](https://github.com/dojo/interop)
- [ ] [`dojo/routing`](https://github.com/dojo/routing)
- [ ] [`dojo/stores`](https://github.com/dojo/stores)
- [ ] [`dojo/streams`](https://github.com/dojo/streams)
- [ ] [`dojo/widget-core`](https://github.com/dojo/widget-core)
- [ ] [`dojo/widgets`](https://github.com/dojo/widgets)
- [ ] [`dojo/test-extras`](https://github.com/dojo/test-extras)
- [ ] [`dojo/web-editor`](https://github.com/dojo/web-editor)

**Comment by dylans** [comment]
All related repos have been fixed, so this is considered finished!
