### ISSUE TITLE
Update package copyright year

### ISSUE THREAD

**Issue by mwistrand** [dojo/meta#230]
Now that it is 2018, the copyright date in each package needs to be updated accordingly. Perhaps there is a tool we can use to automate this process?

- [ ] [@dojo/cli](https://github.com/dojo/cli)
- [ ] [@dojo/cli-build-app](https://github.com/dojo/cli-build-app)
- [ ] [@dojo/cli-build-webpack](https://github.com/dojo/cli-build-webpack)
- [ ] [@dojo/cli-create-app](https://github.com/dojo/cli-create-app)
- [ ] [@dojo/cli-create-theme](https://github.com/dojo/cli-create-them)
- [ ] [@dojo/cli-create-widget](https://github.com/dojo/cli-create-widget)
- [ ] [@dojo/cli-export-project](https://github.com/dojo/cli-export-project)
- [ ] [@dojo/cli-test-intern](https://github.com/dojo/cli-test-intern)
- [ ] [@dojo/compose](https://github.com/dojo/compose)
- [ ] [@dojo/core](https://github.com/dojo/core)
- [ ] [@dojo/has](https://github.com/dojo/has)
- [ ] [@dojo/i18n](https://github.com/dojo/i18n)
- [ ] [@dojo/interfaces](https://github.com/dojo/interfaces)
- [ ] [@dojo/interop](https://github.com/dojo/interop)
- [ ] [@dojo/loader](https://github.com/dojo/loader)
- [ ] [@dojo/routing](https://github.com/dojo/routing)
- [ ] [@dojo/shim](https://github.com/dojo/shim)
- [ ] [@dojo/static-optimize-plugin](https://github.com/dojo/static)
- [ ] [@dojo/stores](https://github.com/dojo/stores)
- [ ] [@dojo/streams](https://github.com/dojo/streams)
- [ ] [@dojo/test-extras](https://github.com/dojo/test-extras)
- [ ] [@dojo/webpack-contrib](https://github.com/dojo/webpack-contrib)
- [ ] [@dojo/widget-core](https://github.com/dojo/widget-core)
- [ ] [@dojo/widgets](https://github.com/dojo/widgets)

**Comment by agubler** [comment]
This is out of date now!
