### ISSUE TITLE
Import variable from external js

### ISSUE THREAD

**Issue by Wokiri** [dojo/meta#235]
I would like to use coordinates generated from a function in a given js file (of which function I have) and use the values to search position in the arcgis map. Any help?

**Comment by dylans** [comment]
Hi @Wokiri this really isn't the right place for this kind of question as this repo is focused on the overall planning for Dojo 2 and beyond. I would suggest asking in https://discourse.dojo.io/ or on Gitter at https://gitter.im/dojo/dojo or perhaps on one of the Esri specific forums.
