### ISSUE TITLE
Dojo application not appear at localhost:9999 after build

### ISSUE THREAD

**Issue by kvstepanov** [dojo/meta#236]
According to [tutorial](https://dojo.io/tutorials/000_local_installation/), after creating new project using cli, and entering `dojo build -w`  command I'll be able to find my app running at localhost:9999, but I'm getting an error: ERR_CONNECTION_REFUSED.

I'm not alone with this issue, here also [question ](https://stackoverflow.com/questions/48548769/i-cannot-get-webpack-to-work)on stackoverflow.

Do I something wrong, or maybe some additional configuration required?

**Comment by agubler** [comment]
Hi @kvstepanov, thank you for raising this issue the tutorial is out of date for the most recent `beta5` release (I'll make sure that's updated). Using the `-w` is for build with `watch` but doesn't automatically serve anymore.

To serve as well the `--serve` (or shorthand `-s`) is required, I hope this helps!

**Comment by agubler** [comment]
have also raised a correction to the tutorial here https://github.com/dojo/dojo.io/pull/376

**Comment by agubler** [comment]
Closing the issue as I think it should be resolved now, please re-open (or raise another issue in the dojo/cli-build-app repo) if you experience further issues. Alternatively you can chat to us about Dojo 2 in the [gitter channel](https://gitter.im/dojo/dojo2).
