### ISSUE TITLE
dojox.charting: MouseIndicator error with empty data set

### ISSUE THREAD

**Issue by gardiol** [dojo/meta#242]
Creating a MouseIndicator on an empty data set result in lots of undefined errors in the console log.
To fix this, it's a very very simple fix in dojox/charting/action2d/_IndicatorElement.js.uncompressed.js at row 305: add "else if ( r )":

`                      if(typeof r == "number"){
                                x = i+1;
                                y = r;
                                if(i > 0){
                                        px = i;
                                        py = data[i-1];
                                }
                        }else if ( r ){
                                x = r.x;
                                y = r.y;
                                if(i > 0){
                                        px = data[i-1].x;
                                        py = data[i-1].y;
                                }
                        }
`

Because if data is an empty list ([]) the above if will end up in the "else" statement and try to assign r.x to x. Changing the "else" to "else if ( r )" fix it without side-effects, at least i can see.

**Comment by dylans** [comment]
This repo is for general Dojo 2 issues... moving this issue to dojo/dojox. If you would like to raise a PR per the contribution guidelines, we'll review it and land it for a future version of Dojo 1.x.

**Comment by dylans** [comment]
Issue moved to [dojo/dojox #279](https://github.com/dojo/dojox/issues/279) via [**ZenHub**](https://www.zenhub.com/)
