### ISSUE TITLE
Pin Node Typings to avoid breakages from 

### ISSUE THREAD

**Issue by maier49** [dojo/meta#247]
We need to pin node typings to `"@types/node": "~9.6.5"` in these repos to prevent/fix breakages from Node 10 types.

- [x] [@dojo/cli](https://github.com/dojo/cli)
- [x] [@dojo/cli-build-app](https://github.com/dojo/cli-build-app)
- [x] [@dojo/cli-build-webpack](https://github.com/dojo/cli-build-webpack)
- [x] [@dojo/cli-create-app](https://github.com/dojo/cli-create-app)
- [x] [@dojo/cli-create-theme](https://github.com/dojo/cli-create-them)
- [x] [@dojo/cli-create-widget](https://github.com/dojo/cli-create-widget)
- [x] [@dojo/cli-export-project](https://github.com/dojo/cli-export-project)
- [x] [@dojo/cli-test-intern](https://github.com/dojo/cli-test-intern)
- [ ] [@dojo/compose](https://github.com/dojo/compose) (skipped: Deprecated)
- [x] [@dojo/core](https://github.com/dojo/core)
- [x] [@dojo/has](https://github.com/dojo/has)
- [x] [@dojo/i18n](https://github.com/dojo/i18n)
- [x] [@dojo/interfaces](https://github.com/dojo/interfaces)
- [x] [@dojo/interop](https://github.com/dojo/interop)
- [x] [@dojo/loader](https://github.com/dojo/loader)
- [x] [@dojo/routing](https://github.com/dojo/routing)
- [x] [@dojo/shim](https://github.com/dojo/shim)
- [ ] [@dojo/static-optimize-plugin](https://github.com/dojo/static-optimize-plugin) (skipped: Deprecated)
- [x] [@dojo/stores](https://github.com/dojo/stores)
- [x] [@dojo/streams](https://github.com/dojo/streams)
- [x] [@dojo/test-extras](https://github.com/dojo/test-extras)
- [x] [@dojo/webpack-contrib](https://github.com/dojo/webpack-contrib)
- [x] [@dojo/widget-core](https://github.com/dojo/widget-core)
- [x] [@dojo/widgets](https://github.com/dojo/widgets) - https://github.com/dojo/widgets/pull/547

**Comment by nicknisi** [comment]
I believe @types/node has now been pinned in all versions.
