### ISSUE TITLE
Consolidate Core packages Into a Single Package

### ISSUE THREAD

**Issue by nicknisi** [dojo/meta#250]
The Dojo team is discussing creating a monorepo for core Dojo packages in #249. With that discussion also comes the discussion of whether we should simplify dojo releases by consolidating the core repositories listed in that ticket as a single dependency.

### Core packages

- [dojo/has](https://github.com/dojo/has)
- [dojo/shim](https://github.com/dojo/shim)
- [dojo/core](https://github.com/dojo/core)
- [dojo/i18n](https://github.com/dojo/i18n)
- [dojo/widget-core](https://github.com/dojo/widget-core)
- [dojo/routing](https://github.com/dojo/routing)
- [dojo/stores](https://github.com/dojo/stores)

## Background
It should be evaluated whether having separate published “core” packages provides value. Most of these packages currently depend on each other and are often required for the optimal Dojo development experience.

## Requirements
- The package name (ideally something like @dojo/dojo) should be consistent with the repository name to avoid confusion, but there are problems with that (see #249).

**Comment by nicknisi** [comment]
@KevinHua Thanks for the feedback! We're thinking along the same lines regarding "@dojo/dojo" and "@dojo/core". In [#249 (Comment)](https://github.com/dojo/meta/issues/249#issuecomment-388860818) we've possibly come to the conclusion that a repo name of "dojo/framework" and package name of "@dojo/framework" might be ideal.

**Comment by agubler** [comment]
Done
