### ISSUE TITLE
Widget design system: Material UI

### ISSUE THREAD

**Issue by smhigley** [dojo/meta#255]
Related to #252 

Look into creating a set of material UI widgets for Dojo, and explore how easily existing Dojo widgets can be modified for material UI. Broad questions that need to be addressed include:

- How flexible is the current approach to widget theming?
- Is it feasible to use themed `extraClasses` as an approach for adjusting minor styles?
- Even if material widgets need to be rewritten, how difficult is it to extend existing widgets to provide reasonable extra functionality, using material as a test case?
- Are the current meta helpers (animation, focus, etc) flexible and easy to use (again using material as a test case)?
- If we adopt atomic design principles, do we include components higher than molecules?
- What new widgets should we add?

**Comment by agubler** [comment]
This has been investigated and will be something that is undertaken and tracked in the `@dojo/widgets` repository over the coming releases.
