### ISSUE TITLE
Update deprecated postcss-cssnext dependency

### ISSUE THREAD

**Issue by dylans** [dojo/meta#262]
Our dependency on postcss-cssnext has been replaced:

```
npm WARN deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
```

- [x] `@dojo/cli-build-app`
- [ ] `@dojo/cli-build-widget`
- [ ] `@dojo/themes`
- [ ] `dojo/grunt-dojo2/`

**Comment by dylans** [comment]
Changes to @types/source-map moved to https://github.com/dojo/cli-test-intern/issues/107

**Comment by agubler** [comment]
`postcss-cssnext` has been replaced with `postcss-preset-env`
