### ISSUE TITLE
Migration to typings

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#27]
We should consider migrating to [typings/typings](https://github.com/typings/typings) for type management for Dojo 2.  It solves some of the challenges that TSD and the other sort of issues that can occur with complex type management and dependencies.

**Comment by kitsonk** [comment]
Actually, we *need* to do it, since DTS and DefinitelyTyped  have been officially deprecated by the TypeScript team in lieu of typings/typings.

**Comment by Tomdye** [comment]
Worth noting this may be part of the transition for `dojo-core`: https://github.com/dojo/core/issues/162

**Comment by vansimke** [comment]
@kitsonk Could you take a look at https://github.com/vansimke/core/tree/meta_issue_27 and let me know what you think? Everything seems to work except from `grunt dist_esm` which is running into some weird errors during compilation that I didn't have time to dig into today.

**Comment by kitsonk** [comment]
@vansimke, thank you! It is fine to leave it without `grunt dist_esm` for now and we can enhance that over a period of time.  Most of it will because you are loading some typings at compile time that are duplicates of what is defined elsewhere.  There is no easy way to deal with different sets of typings with different targets at the moment yet that I am aware of.

Couple notes though:

* I would prefer we find more respectable places to pull the typings from the previous history of the repo.  For all the ones that aren't well published at the moment (or we have to use a custom version like node), we should add them to `dojo/typings/custom` and reference them there.
* Also, we will need to supply the `symbol-shim` as it will be needed by downstream packages that are targeted at ES5.
* While you excluded the `/typings` from `.gitignore` you still have some files checked into those paths.  That will leave them "abandoned" and never updated. You should `git -rm /typings/` and `git -rm /tests/typings/`
* I would also do an `npm pack` on the package which will produce a `.tgz` which would represent what we publish on npm.  I would extract that then and validate that it has the files in way you expect and nothing you don't expect or like.

**Comment by kitsonk** [comment]
A [consolidated diff](https://github.com/dojo/core/compare/master...vansimke:meta_issue_27) if anyone else wants to have a look.

**Comment by vansimke** [comment]
Yeah, I was only trying to get a straw man out there. I'll clean things up and then submit a PR for it.

**Comment by vansimke** [comment]
I've made some updates to my [fork](https://github.com/vansimke/core/tree/meta_issue_27), but I'm not happy about where things are at. Currently, due to the conflicts between the different typings (which is exacerbated by including symbol-shim), `npm install` fails due to conflicts in `grunt dist`. I think that it is related to [this](https://github.com/dojo/core/issues/149) issue, and I couldn't figure out how to get around it. Somehow dojo/core:master works, but as soon as I change from tsd to typings/typings, it starts to complain.

If we're okay with this direction, then I can submit a PR to dojo/typings to add the new typings that I need to centralize the non-published type definitions and then update this branch to point to those definitions.

**Comment by kitsonk** [comment]
@vansimke sorry to send you on a fools errand.  I am in the process of adapting dojo-core, because we need to get a new release out for some downstream development.  I apologise too much of this is in my head at the moment to be able to effectively get someone else to be able to address it, but I suspect it will just be easier for everyone if I just finish it off.

**Comment by kitsonk** [comment]
Actually we have completed this work, though we now need to migrate to `@types` (just in time)
