### ISSUE TITLE
Elect / Nominate representative(s) to the OpenJS Foundation CPC 

### ISSUE THREAD

**Issue by jorydotcom** [dojo/meta#270]
(reposted from the wrong repo, sorry!!)

## Context
As part of the new [OpenJS Foundation's bylaws](https://github.com/openjs-foundation/bootstrap/blob/master/artifacts/OpenJS-Foundation-Initial-Merged-Bylaws.pdf), the Cross Project Council (CPC) has been [chartered](https://github.com/openjs-foundation/bootstrap/tree/master/proposals/stage-2/CPC_CHARTER) to serve as the primary governing body for programs and regular support of Foundation projects. For example, it will be responsible for things like infrastructure, travel assistance, CoC support, accepting new projects into the foundation, and mentorship programs to name a few. It will also be responsible for electing board representative(s) to the OpenJS Foundation board of directors.

**Any interested person from our project communities can attend CPC meetings and volunteer to participate in tasks.** For most programs, the CPC is expected to operate on the consensus of OpenJS Foundation project members. Issues that require a vote - namely the election of Board representatives and accepting a new project - will be memorialized by a voting CPC membership comprised of up to 2 representatives from Impact level projects and 2 representatives from Growth and At-Large stages.

If you'd like more info/context on the governance of the OpenJS Foundation, please let me know or follow this repo. The main point I hope you take away is that the foundation is to be run by and for the projects, and to do that we need participants from the project community.

## Request
As an Impact level project, Dojo is expected to send up to two formal representatives to participate in CPC meetings in a voting capacity. We (the bootstrap CPC group) would like you to make this selection by May 1. You can do that in whatever fashion you would like (projects retain their [own internal governance](https://thumbs.gfycat.com/CraftyBoilingCornsnake-small.gif)).

We anticipate having our first 'official' CPC meeting on May 30 or 31 at the Collaborator Summit in Berlin (sidebar, you should come!). In the interim, we would love for Dojo project members to participate in the Bootstrap CPC meetings which are currently held on Mondays (watch [this repo](https://github.com/openjs-foundation/bootstrap/issues/150) for meeting details).

If this is not the correct forum to raise this, please let me know and I will close the issue and post it in the preferred channel. Note that I'm posting essentially the same message to all OpenJS Foundation project repos, because I want to get the word out and make sure we all have the same information. 

your pal,
Jory

**Comment by jorydotcom** [comment]
Hi Dojo team! Any updates to share here? As an FYI, if you don't think this is something Dojo wants to commit to doing as an Impact project, we can always change status to At Large or Growth which do not have the same expectations for participation. LMK what you're thinking, if you want to chat sometime!

**Comment by dylans** [comment]
Hi Jory, sorry for the delay, we've been reviewing the details and discussing what needs to get done on our end. For the most part I think we're ok, with the one exception that I've mentioned to you (active development and contributions are currently skewed towards one company, so we need to discuss what we can do about that... we don't expect it to be that way forever, just that it has been that way with the big transition from Dojo Toolkit to modern Dojo). We do want to participate, it's just been a hectic few weeks, and Mondays are really bad for meetings which is why I've not been able to attend any of the bootstrap CPC discussions. :( But assuming we can find a solution for the governance situation, I think we'd still like to be an impact project, though it may be simpler to consider one of the other options. We'll let you know asap.

**Comment by jorydotcom** [comment]
Okiedok, @dylans - thanks for the update! We are looking to change the meeting days/times in the next couple of weeks - take a look and update the two tabs on [this spreadsheet](https://docs.google.com/spreadsheets/d/12e8lN9ywi-2kAtcW08WS3x3S-6TXiOO8_yxs3j0Sm2E/edit#gid=0) with your availability if you don't mind!
