### ISSUE TITLE
ES6 Typings

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#29]
As discussed in #18, we have scenarios where when having ES6+ targetted code versus ES5 targetted code, the typings have to be different.  Even with shimming the way we do, we run into issues when targetting ES6 (for example TypeScript complains when you aren't using the native `Symbol` when you target ES6) and it is difficult to deal with `Iterators`.  @devpaul pointed out that ReactiveX/RxJS (who likely have some of the most mature) have to "cheat" by typings things as `any`.

We think Conditional Decorators [Microsoft/TypeScript#3538](https://github.com/Microsoft/TypeScript/issues/3538) and Micro Targetting [Microsoft/TypeScript#4692](https://github.com/Microsoft/TypeScript/issues/4692) will potentially provide us with the tooling to make it easier to generate ES6 code as well as generate the correct corresponding typings.

We should also check out how [typings/typings](https://github.com/typings/typings) will help manage these situations, to understand if different targeted versions of typings can be made available to be consumed.

**Comment by devpaul** [comment]
We can accomplish this today without Conditional Decorators and Micro Targeting by externalizing all of our interfaces and making our types generic. For example with array.from

```typescript
// in array.ts
from<T>(arrayLike: Arrayish, mapFunction?: MapCallback<T>, thisArg?: {}): ArrayLike<T>

// in array.es5.d.ts
declare type Arrayish = string | ArrayLike<T>;

// in array.es6.d.ts
declare type Arrayish = string | ArrayLike<T> | Iterable;
```

When compiling we would include *.d.ts and *.es5.d.ts typings when targeting es5 and *.d.ts and *.es6.d.ts when targeting an es6 build. This increases typing complexity the more platforms we target, but should be achievable within current constraints.

We will still need to solve providing ambient typings to the typings repo.

**Comment by dylans** [comment]
We should probably revisit this in the context of supporting ES6 versions of Dojo 2.

**Comment by kitsonk** [comment]
This is sort of unactionable at the moment.  There is no clear path of how we

With the latest version of `@dojo/shim` downstream projects can target easily in ES2015+ for the emit, but the Dojo 2 packages are still ES5.  At the moment, I don't think there is really anything more we can easily do... the "build dojo 2 from source" use case _might_ eventually be valid, but still the complexity isn't worth the squeeze.  Long live the transpiler.  Closing...
