### ISSUE TITLE
Build time concatenation/layering

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#34]
The Dojo 2 build system should allow a developer specify concatenation/layering of modules to create a _built_ output of an application.

**Comment by Tomdye** [comment]
# Overview
Aim is to avoid the need to write a new solution from scratch.
Considerations are
	- [webpack](https://webpack.github.io/)
	- [r.js](http://requirejs.org/docs/optimization.html)

Test app is the `widget example app` [here](https://github.com/kitsonk/app-example).

## Webpack
'Bundles' up modules and is capable of building optimised 'chunks' for single page applications. Doesn't play nicely with our `AMD` plugin modules.
We would need to write a custom `loader` for out dojo2 modules and plugins similar to this [`dojo-webpack-loader`](https://github.com/Nordth/dojo-webpack-loader) on github.
Uses a `webpack.config.js` file, when present, build is triggered by calling `webpack`.

Sample config file:
``` javascript
module.exports = {
	entry: __dirname + "/_build/src/index.js",
	output: {
		path: __dirname,
		filename: "index-webpack.js"
	},
	resolve: {
		alias: {
			"src": ".",
			"dojo-actions": __dirname + "/node_modules/dojo-actions",
			"dojo-compose": __dirname + "/node_modules/dojo-compose",
			"dojo-core": __dirname + "/node_modules/dojo-core",
			"dojo-widgets": __dirname + "/node_modules/dojo-widgets",
			"immutable": __dirname + "/node_modules/immutable/dist",
			"maquette": __dirname + "/node_modules/maquette/dist",
			"rxjs": __dirname + "/node_modules/@reactivex/rxjs/dist/amd"
		}
	}
};
```

Throws errors with our `has!` and `text!` usage as noted above.
This setup currently does not work.

## r.js
Creates a built version of a given `.js` file and it's dependencies and works great with AMD. Has optimisation built in so can run the code through `uglify` automatically. 

We will need to adopt the [`requirejs`](http://requirejs.org/docs/plugins.html#apiwrite) build time plugin resolution approach, an issue has already been created for this [here](https://github.com/dojo/loader/issues/31).

Uses a build profile file, can support layering. Sample file:

``` javascript
({
	baseUrl: ".",
	paths: {
		"src": "_build/src",
		"dojo-actions": "node_modules/dojo-actions",
		"dojo-compose": "node_modules/dojo-compose",
		"dojo-core": "node_modules/dojo-core",
		"dojo-widgets": "node_modules/dojo-widgets",
		"immutable": "node_modules/immutable/dist",
		"maquette": "node_modules/maquette/dist",
		"rxjs": "node_modules/@reactivex/rxjs/dist/amd"
	},
	name: "_build/src/index.js",
	out: "_build/src/index-built.js"
})
```

The example app loads successfully with this built file, but the maps to the `min` versions of certain files need to be turned off.

## Suggested next steps
Proceed with using `r.js` for our builds, however I believe that going forward we will need to provide guidance on how best to use `dojo2` with webpack in custom projects. This will most likely be using a build version of `dojo2` such that the plugin issues do not arise.

**Comment by taoqf** [comment]
i tried to use webpack and i found errors(warning):
1.request error eg.`require.on('error',(ex)=>{});`
2.ts(and d.ts) error, i tried use ts-loader, did not work.
3.other errors(like package.json and licence),  which i have no idea where they came from.
4.it seems that webpack could not deal with 'umd' rightly.

does dojo-cli intent to to the building stuff?

**Comment by Tomdye** [comment]
@taoqf we discovered issues using webpack with our `AMD` plugins and as per the `Suggested next steps` above, we're currently proceeding with using `r.js` for our builds.

**Comment by rishson** [comment]
Tracking work at dojo/cli#59

**Comment by agubler** [comment]
Closing in favour of tracking issues against [cli-build](https://github.com/dojo/cli-build)
