### ISSUE TITLE
Build time minification

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#35]
The Dojo 2 build system should allow minification of the final outputted code, ideally using [Uglify 2](/mishoo/UglifyJS2)

**Comment by Tomdye** [comment]
# Overview
In order to provide the smallest possible download size we need to provide `js` optimisation as part of our build.

Initial considerations:

- [Google closure compiler](https://github.com/google/closure-compiler)
- [uglifyjs2](https://github.com/mishoo/UglifyJS2)

Both of these are supported by `r.js`.

**Comment by kitsonk** [comment]
Yes, I think those are both good considerations.

Here are some thoughts off the top of my head:

* closure compiler requires Java where as Uglify is fully JavaScript
* Both the jQuery Foundation and the Dojo Foundation (now combined) have supported development of Uglify in the past
* We have integrated Uglify into the [dojo/loader](https://github.com/dojo/loader/blob/master/Gruntfile.js#L265)

I am not currently aware of any features that we would use of closure compiler that are not present in Uglify.  It would be good to focus on any potential advantages of closure that are missing from Uglify.

**Comment by Tomdye** [comment]
Agreed Kit.
Worth noting that `r.js` can automate the process through either of them.
There's a few interesting comparisons between the two out in the wild:

- https://www.peterbe.com/plog/advanced-closure-compiler-vs-uglifyjs2
...more to come

The argument re. java is probably one of the main ones. The opinion in comments fields for various comparisons seems to be that people aren't too bothered about **build time** differences which is worth noting.

**Comment by kfranqueiro** [comment]
I seem to remember quite a few visitors to #dojo on IRC over the years to which build time differences are a *big* deal, and IIRC uglifyjs can make a huge difference over closure in that regard.  There are other things outside of this particular discussion that we could potentially do to improve that too though, like not copying and scanning every single module in every package the build is told about.

**Comment by Tomdye** [comment]
Thanks @kfranqueiro, good to know. 
If there's any other alternatives you can think of or any info to point me at please do. r.js supports either as part of it's optimisation stage so it probably wouldn't be too much trouble to support / tolerate either

**Comment by rishson** [comment]
@matt-gadd can you create an issue in `dojo/cli` if we still need to implement anything other that what is provided by webpack? Otherwise, we can close this off.

**Comment by matt-gadd** [comment]
@rishson we need to create an issue to track the changes needed to build as `dojo/app` changes have resulted in us not being able to build projects anymore. this might even end up as re-evaluating whether we use webpack.

**Comment by agubler** [comment]
This is no longer relevant.
