### ISSUE TITLE
dojoReady?

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#41]
@taoqf commented on [Fri Apr 22 2016](https://github.com/dojo/dom/issues/48)

in which packge can i find this?
i find it in dojo/dojo2 which says`This repository is not part of what will become Dojo 2. We are not looking for contributions to this repository. If you wish to use or contribute to Dojo 2, please visit dojo/meta to find more information on the current status and packages of Dojo 2`

**Comment by kitsonk** [comment]
What specific use case are you trying to solve?

We have avoided moving forward with functionality like that until we had a clear use case we could not solve another way, as it was rather confusing part of Dojo 1 that led to a lot of users not using it properly and actually causing themselves issues.

**Comment by taoqf** [comment]
i want to do something when the page is ready, which i used `dojo/ready` and `dojo/domReady` in dojo1.x, what should i do now? @kitsonk

**Comment by kitsonk** [comment]
Like what specifically?

That is/was the challenge, in a lot of cases people believed there was some sort of "magic" that they needed.  Because we recommend placing the `script` tag to load the loader and any modules at the end of the document's `body` in order to improve the user experience when loading the page, these sorts of things become irrelevant.

**Comment by dylans** [comment]
Or of course in the head while using the HTML async attribute.

Once AMD was fully implemented and some edge cases were fixed with Dojo 1.x, the only real purpose for dojo/domReady! was to prevent issues where someone would try moving their require block into the head.

**Comment by kitsonk** [comment]
I am going to close this for now until we find a compelling use case.  I realise it is "different" than Dojo 1, but there will likely be quite a lot of those and we need to be conscious of this when creating migration guides.
