### ISSUE TITLE
Bower and Dojo 2

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#47]
We need to really come up with what we are going to do with Bower.  Obviously there is a big cowpath (🐮 :car:) to npm, but we need to figure out how we are going to publish to Bower.  Now that we have reworked the distributions, it should be in a stable situation to properly consider this now.

**Comment by matt-gadd** [comment]
Given the path we've gone down with typescript `node` resolution, and `@types`. And with `yarn` now out and supporting flat packages (probably the only thing bower had going for it). Is this still a valid objective?

**Comment by edhager** [comment]
It looks like the decision has been made to not support Bower: #118

**Comment by rishson** [comment]
Closing for reasons stated by @matt-gadd.
