### ISSUE TITLE
Dojo - 2 getting started/developer setup

### ISSUE THREAD

**Issue by gbaumgart** [dojo/meta#51]
hi,

i am watching/experimenting with dojo2 since quite a while now and the most frustrating part is "Getting Started" at all. I understand its all alpha/beta but  I'd like to get something working at all.

Whatever tsc version i used with whatever directory structure (as submodules, npm installs) i tried : grunt tasks just fail nor i could get anything running with latest PHP/Webstorm setups. I spent days now in total and every time I got something running, it gets broken with the next npm update/git pull. It also doesn't matter I use source or dist versions.

I have this result for small tests (trying a single dojo/module) or Kitsonk's app-example (which just fails with grunt already)

So, do you have by chance a pointer how to use that new modules? It seems that you're using very special editors and/or background tasks to get your code running and compiled. 

Us, we just want use our prefered IDEs (JetBrains) with their special support for Typescript which works very well with our own typescript modules. 

I can post you all the error logs of Jetbrains but I guess its not the point. 

The problem is basically, if we can't start playing with dojo-2, or start migrating parts of our code base, the switch becomes even a bigger problem. 

well, close this if its too early asking such thing but yeah, any pointer how you get this things working would be great to know.

thanks,
g

**Comment by gbaumgart** [comment]
most fixes i have to do are always in your tsconfig.json to make JetBrains happy: 

```
"paths": {
      "dojo-core/*": [
        "dojo-core/src/*"
      ],
      "dojo-loader/*": [
        "dojo-loader/src/*"
      ],
      "dojo-compose/*": [
        "dojo-compose/src/*"
      ]
    }
```

but this requires typescript@next (1.9 or so)

**Comment by kitsonk** [comment]
It is really a bumpy ride at the moment, and we apologise for that.

In a lot of cases, when the packages are quite fluid, we have been successfully using symlinks to go to builds of the packages that are build off master.  So it would be cloning all the main repos that are needed and then from the "app" directory, going into `node_modules` and symlinking back to the clone repos.  Most of the repos should build a proper "build" distribution when you do an `npm install`.

I need to update `kitsonk/app-example` as we have published some packages that are then "breaking" things in that example.

@Tomdye and @agubler are working on tooling for what we think will make scaffolding quite a bit easier.  The current WIP is at [dojo/cli](https://github.com/dojo/cli).

@novemberborn is getting close to landing the last big piece we need to have what we consider a viable "framework" ([dojo/app](https://github.com/dojo/app))

Yes, the paths will make some use cases easier, but not all our repos are "TS2" safe at the moment, so you may get strange behaviours.

Feel free to ask questions though... in some cases the answer is going to be ¯\\\_(ツ)_/¯ though at this point in time.

**Comment by gbaumgart** [comment]
Hi, thanks a lot for the heads up, no worry, i understand perfectly in what sort of mess we are with es6.

ok, that symlink story makes sense because i got also much better results with ditching the repos via sub modules in my test app.

Ok, i will try to use the ideas of dojo/cli. i guess that will clear things for me and so i can adjust my own tools to get dojo2 modules working. 

gonna close this for now. basically i have to write as next a sort of getting started guide for our-self and if it got any stable or reliable, i will post it here. and if possible, have a look from time to time with Jetbrains & TS enabled on your modules, you will see how awful/confusing things can get.

thx again,
g
