### ISSUE TITLE
Widgets and Language Resources

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#56]
How does the i18n solutions fit into the widgeting system?  One of the main purposes of the shadow DOM was to allow such sorts of substitution, but considering the Dojo 2 widgeting system is based on a virtual DOM, how best should i18n be integrated into the widgeting system?

**Comment by mwistrand** [comment]
I'm still in the process of tracing how everything within a [Dojo App](https://github.com/dojo/app) flows so I can actually offer cogent implementation suggestions, but after looking through [Dijit](https://github.com/dojo/dijit), documents from the W3C, and drawing from my own history with i18n, I'm wary of trying to make too many assumptions directly within the `dojo/widget` package beyond providing an additional layer that allows each widget to control its own `i18n: { direction, locale }` state, and updates the `dir` attribute on the root node when necessary (with care being taken to ensure children inherit from the parent unless they explicitly have their own text direction and/or locale).

## Setting the locale/text direction

When an app is created, the base locale and text direction can be set by passing an `i18n: { locale, direction}` object to [`createApp`](https://github.com/dojo/app):

```
createApp({
  i18n: {
    locale: 'ar-JO',
    direction: 'rtl'
  }
});
```

This would result in the `<body>` element being decorated with a `data-locale="${i18n.locale}"` attribute (more on this below), and the `<html>` element being decorated with a `dir="${i18n.direction}"` attribute. If the app creator wants to prevent the scrollbar switching sides when `dir="rtl"`, then the `direction` property can be excluded, in which case the `dir` attribute must be added manually to the appropriate elements. The app creator is also responsible for ensuring the appropriate `<meta charset>` is added to the markup.

Beyond the update to the `AppOptions` interface, each widget store can accept the same `i18n` object, overriding the locale and/or text direction for just that widget. Specifying a custom locale would result in `data-locale` and `dir` attributes being added to the widget's root node.

## The `data-locale` attribute

There is the possibility that app creators/consumers will come across instances in which the existing design falls short of delivering an excellent experience to users of a specific locale. In such cases, accommodations may be needed to the design. Initially I thought a CSS class might suffice, but given the complexity allowed within a [BCP 47 language tag](https://tools.ietf.org/html/rfc5646), using a data attribute is more flexible, as it allows more complicated selectors:

```css
[data-locale="^ar-"] {
  /* custom styles */
}
```

NOTE: the exact implementation details of this may change depending on the resolution to [dojo/meta # 28](https://github.com/dojo/meta/issues/28).

**Comment by mwistrand** [comment]
Once [`dojo/i18n` #11](https://github.com/dojo/i18n/pull/11) lands, widgets can load their own messages with a function call that returns a promise:

```typescript
import i18n from 'dojo-i18n/i18n';
import createRenderMixin from 'dojo-widgets/mixins/createRenderMixin';
import bundle from 'path/to/nls/bundle';

const createWidget = createRenderMixin
  .mixin({
    render() {
      return i18n(bundle, this).then((messages: Messages) => {
        // return VNode
      });
    }
  })
```

By passing themselves to the `i18n` function, widgets will be registered with the i18n system and `invalidate` when the locale is changed. However, unless I am mistaken, at the moment `render` expects a synchronously-returned VNode object, and cannot return a promise. So either we would need to use a different place to retrieve messages, or the widgeting system would need to be updated to allow `render` to return a promise.

My earlier suggestion to go through `dojo-app` is unnecesary, since `dojo-i18n` can be used directly. But we will still want a mixin to at least set the `dir` attribute as needed, and also to set a `data-locale` attribute as I suggested above.

**Comment by rishson** [comment]
Closing as we have an initial implementation of `i18n` in widget now.
