### ISSUE TITLE
queue in dojo/shim and dojo/core

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#60]
When splitting out the shims from core, there were two APIs that they shared, `has` and `queue`.

When it was refactored, we agreed to split out `has` because we could see this quite easily as a generic API that stood on its own.

The `queue` that is in `dojo/shim` is the minimal version of the API from `dojo/core` and is only used by `Promise` to schedule executors.  Like has, it is a supporting API that isn't part of the exposed API (although shim/has does have some feature flags defined which are then used in other packages).

The `queue` in `dojo/core` serves a few purposes. One it provides an external API for other to consume to schedule callbacks asynchronously, but it also is used in other parts of core to provide functionality.

I see three options of what we can do:
- Leave it as it is, which means that we would duplicate code/API between core and shim.  While this is generally anti-pattern, there are worse sins in the world and is limited to a very specific narrow bit of code.
- Export queue from dojo/shim and re-export it from dojo/core.  Again anti-pattern, where the API is defined in a wholly unrelated package.
- Break out queue into a separate package.  This just increases the overhead of managing things and only reinforces that we sort of need good tooling to make this manageable for the end developer.

**Comment by rorticus** [comment]
PRs here,

https://github.com/dojo/core/pull/282
https://github.com/dojo/shim/pull/72

**Comment by rorticus** [comment]
PRs are merged!
