### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#61]
We should define a code of conduct for the Dojo Toolkit. I have thought about it for a while but it would codify the way we have managed the community from the start.

**Comment by agubler** [comment]
@rishson how are we coming on with the code of conduct?

**Comment by rishson** [comment]
@agubler I did look into this. My proposal is to create a coc based off of: http://todogroup.org/opencodeofconduct/

@dylans we would need to specify contact details for those wishing to report violations. Do you have any prefs for the email used?

**Comment by dylans** [comment]
@rishson in general I'd prefer a contact form (or a form that adds responses to a google doc) rather than a published email address which will just turn into a pile of spam...
