### ISSUE TITLE
Unable to create relative source map Urls with TS2.0

### ISSUE THREAD

**Issue by agubler** [dojo/meta#67]
It looks like changes in TS2.0+ prevent a relative sourceMapUrl from being generated despite the adding the `mapRoot` attribute in the `tsconfig.json`. Issue raised with typescript https://github.com/Microsoft/TypeScript/issues/10612

**Comment by matt-gadd** [comment]
Given the release of the 2.0 RC is it worth us dropping the moving of sourcemaps to the `_debug` temporarily? It's not great losing sourcemaps, and I'd be reluctant to write any custom fixer in `grunt-dojo2` that will ultimately be redundant.

**Comment by agubler** [comment]
I inclined to agree, we can also add this back in once TS2 supports the relative mapping again.
