### ISSUE TITLE
Convert all packages to publish as flat umd

### ISSUE THREAD

**Issue by matt-gadd** [dojo/meta#68]
Convert all dojo2 packages to flat umd.

For the migration the following changes are required:

* Make sure the `package.json` is formatted to `npm` standards (2 spaces per indent)
* Modify `package.json`:
	* add `private` key and set to `true`
	* change `main` from `index.js` to `main.js`
	* remove `dist` from `prepublish` in `scripts`
	* remove `typings` key
	* change `typescript` version to `2.0.2`
	* change `grunt-dojo2` version to `2.0.0-beta.16`
	* remove `index.js` from `files` if it exists
* Delete `index.js`
* Remove `index.js` from `tsconfig` `files` if there
* Remove any `dojo` deps from the `paths` in `compilerOptions` of `tsconfig.json`
* Rename any occurences of `maquette/maquette` to just `maquette`
* Rename any occurences of `immutable/immutable` to just `immutable`
* Adjust `intern.ts` loader `packages` for the following to:
```
{ name: 'immutable', location: 'node_modules/immutable/dist', main: 'immutable' },
{ name: 'maquette', location: 'node_modules/maquette/dist', main: 'maquette' }
```
* Adjust `intern.ts` loader `packages` for dojo deps to: 
```
{ name: 'dojo-{depName}', location: 'node_modules/dojo-{depName' }
```
* If the functional tests are bad and include a loader config per file ie https://github.com/dojo/core/blob/master/tests/functional/text/textPlugin.html#L16, you will have to fix those configs like above also
* Drop the `extra-immutable` and `extra-maquette` from typings
* If in a repo that has an actual resulting example (ie dojo/widgets, todo-mvc), change the above packages in the config like done in `intern.ts`.

After the above changes, you can release the package using the grunt release task:
* Perform a dry run `grunt release --pre-release-tag=${tag} --dry-run` where `${tag}` can be alpha, beta, rc (double check the package in dist is correct in shape, and that the package.json is correct in the repo as well as in the package)
* Perform the release `grunt release --pre-release-tag=${tag}` where `${tag}` can be alpha, beta, rc
* Check the commit history for the correct version commits
* Check that a git tag has been created
* `git push && git push --tags`

**Comment by matt-gadd** [comment]
Status: 
- [ ] dojo/has
- [ ] dojo/shim
- [ ] dojo/core
- [ ] dojo/compose
- [ ] dojo/dom
- [ ] dojo/routing
- [ ] dojo/app
- [ ] dojo/widgets
- [ ] dojo/examples

**Comment by rishson** [comment]
How should we divvy this up then? Someone going to go through and do all, or assign out to individuals?

**Comment by agubler** [comment]
I'm working through these now.

**Comment by matt-gadd** [comment]
@rishson nothing to divvy up, me and @agubler are working on these now

**Comment by rishson** [comment]
Great! Can you estimate please.

**Comment by agubler** [comment]
already done @rishson

**Comment by agubler** [comment]
All modules completed.
