### ISSUE TITLE
Parent/Child Widgets and State

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#71]
There are several thoughts on how widgets and state should be dealt with.  In my opinion, there are three different types of parent widgets:
- **Composite Parents** - Where the parent has one to many children, of which the state of the parent is intrinsically tied to the state of the children.  One could say that the parent could actually "render" the state of the children when its state is rendered (e.g. for any given state of the parent, the state of the children could be known).  For example a Todo Item, where it useful to encapsulate the completed checkbox logic in a full widget instead of rendering the whole of the VDOM representation in the parent.
- **Class Parents** - Where the parent has _n_ children that are of all of the same class (e.g. a list widget) of which the parent could be responsible for instantiating those children by interpretation the its state, but one instantiated, the child's state is independent of the parent.  The parent could also be responsible for destroying any children based on its state. For example, a list of Todo Items.
- **Parents** - This is a parent where it own any number of children, of any class, and is only concerned about rendering its children appropriately and the state of the children is wholly independent of the state of the parent.  For example, a Tabbed Panel.

For _Parents_, it is obvious that the state of the parent and children are completely independent and an external controller instantiates and mutates the state of the parent and the children.  The widget may fire actions that logically mutate the state of the children (e.g. a close button) though the actual mutation would be controlled externally.

For _Class Parents_, the question is does it make sense for a parent to know what class its children is and manage in the instantiation of those children and if observing its state or interacting with a registry, instantiate those instances with the registry, thereby "filling out" the initial state of the child widget?  Also should a parent destory instances when that instance is no longer represented in its state?

For **Composite Parents**, it is my opinion that the parent should fully manage the instantiation and destruction of the child widgets, as well as encapsulate the logic of the mutations to the child state and the the child state should not persist anywhere (because given _X_ parent state, the child state would always be _Y_).  External controllers should only worry about mutating the state of the parent, knowing that the rendered state of the child would always be determined by the parent.

**Comment by dylans** [comment]
This has been resolved through recent work on widgets!
