### ISSUE TITLE
Update Publishing Package Instructions

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#80]
Update the [Publishing a Package on npm](https://github.com/dojo/meta/blob/master/documents/Committer-Workflow.md#publishing-a-package-on-npm) section of the Committer Workflow to reflect the `grunt-dojo2` release process.

**Comment by matt-gadd** [comment]
I believe @agubler has mostly resolved this by writing docs for the `release` task in https://github.com/dojo/grunt-dojo2/pull/62. Perhaps we simply add a link to that in the Committer Workflow?

**Comment by agubler** [comment]
This is covered in https://github.com/dojo/meta/issues/72
