### ISSUE TITLE
Accessibility (a11y)

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#82]
# User Story

Developers need to produce accessible applications, whether they realise it or not.  Dojo 2 applications should be accessible by default, with an end developer not having to do much, if anything, to generate an accessible application.

This Epic contains the issues related to accessibility (a11y) for Dojo 2 applications, which is mainly focused around making sure widgets are accessible as they are the parts of the Dojo 2 application exposed to the user.

**Comment by rishson** [comment]
moved to `beta3` as some related issues are not `beta2`

**Comment by kitsonk** [comment]
All sub issues have been addressed, closing and we can tackle anything further on a per issue basis.
