### ISSUE TITLE
Dojo 2 and PWA/Service Workers

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#83]
There are several things we should consider related to PWA and Service Workers for Dojo 2.  This is the Epic and main discussion issue for that.

**Comment by dylans** [comment]
https://github.com/googlechrome/lighthouse (dev tool from Google for auditing and measuring PWA)

**Comment by rishson** [comment]
I've added issues for the 'implementable' parts of initial PWA support.
Additional concerns:
- check our widgets are responsively designed
- check we don't cause any mixed content warnings when running over https
- run lighthouse

**Comment by rishson** [comment]
[This](https://github.com/pinterest/service-workers/tree/master/packages/service-worker-plugin) may be of interest.

**Comment by kitsonk** [comment]
In the design meeting of 3 Aug 2017 we decided that our general approach to enabling service works was through the `@dojo/cli-build-app` command.  We would add an appropriate options to the `.dojorc` for the build application to support this to ensure that an application being built that is flagged as a PWA application is built appropriately.  This includes a few concepts:

* We shouldn't modify `@dojo/cli-create-app` unless absolutely necessary.
* PWAs should be opt in, not scaffolded out by default
* The build step should ensure that everything conforms and/or generates necessary items as directed by `.dojorc` for the project, assuming _intelligent defaults_

**Comment by kitsonk** [comment]
Let's tackle a holistic solution for PWA support in the RC at the earliest.

**Comment by kitsonk** [comment]
Adding to re-architecture of CLI Build epic as it is likely to address all of these issues.
