### ISSUE TITLE
Support for third-party theming systems?

### ISSUE THREAD

**Issue by dylans** [dojo/meta#85]
Should we provide a way to use third-party theme systems with Dojo 2? e.g. bootstrap, material design, etc.? I see this as somewhat orthogonal to CSS modules and the default theme implementation.

Use case: Someone is migrating an app from something else where they've leveraged a CSS framework, and we want to minimize their efforts in making the new app look and feel like their old app?

**Comment by rahmanha** [comment]
This will be a very nice feature for Dojo. For instance, I use Bootstrap and like its “responsive web design” property a lot. If I may use Bootstrap with Dojo, that will indeed be a great pleasure. In such case, Dojo could be powerful engine behind Bootstrap. Accordingly. I think having a feature of a pluggable third-party theming system mechanism for Dojo will significantly increase its usefulness.

**Comment by sebilasse** [comment]
loving semantic-ui.com and the idea of https://react.semantic-ui.com
and I think http://typestyle.io/#/ has a pretty nice API (also regarding server side rendering)

**Comment by kitsonk** [comment]
I feel this is a really long grass item and rather vague.  Supporting _n_ number of 3rd party themes is rather impractical.  If there is a desire for supporting a particular 3rd party theme, then we should open a specific issue in `widgets-core` and even then, it is likely to be much more of a widget community effort to do that, which can be done one off by creating a map that would be something like this:

```js
{
    "dojo-button": { "root": "some-other-class-name" }
}
```

That would be loaded and supplied as the `theme` option to a widget properties.

We may create tooling which provides the sort of structure for a theme, but again that is in the long grass.
