### ISSUE TITLE
Integration to 3rd Party Diagnostic Solutions

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#88]
Is there a need to provide packaged integrations to solutions like Track.js, or is that something best left for the wider community or HOW TO guides?

**Comment by rishson** [comment]
Adding popular 3rd party services:

[Rollbar](https://rollbar.com/docs/notifier/rollbar.js/)
[Honeybadger](https://www.honeybadger.io/for/javascript/)
[Track.js](https://trackjs.com)
[Bugsnag](https://bugsnag.com/platforms/javascript/)
[NewRelic](https://newrelic.com/browser-monitoring)

and

Google analytics
Homegrown http POST to endpoint

**Comment by rishson** [comment]
Things to consider:

- App author has to include client lib (`rollbar.js`) and bootstrap snippets etc
- We will need a `configure` function that takes an API key. Should we support something in our `dojo build` that inlines API keys from `.env` files etc?
- We could offer a standard API around `FATAL, ERROR, WARN, INFO, DEBUG` and convert to equivalents (e.g. for WARN, call `rollup.warn()`, call `honeyBarger.notify('WARN', ...)`).
