### ISSUE TITLE
Update widgets/README with the planned approach to form validation and management.

### ISSUE THREAD

**Issue by dylans** [dojo/meta#94]
This ticket is a placeholder to remind us to:
- Explain how form validation works with Dojo 2.
- Determine if it makes sense to infer some validation rules from types (though types don't give us constraints on data within a type, so probably not).
- How does someone create forms with interdependent fields?

**Comment by kitsonk** [comment]
This feels disconnected... "form validation" implies a solution, not the problem, which is validating user input.  I strongly believe that this is something that should be addressed in a tutorial instead of a readme.

Closing in favour of dojo/dojo.io#152
