### ISSUE TITLE
Helping users create performant applications

### ISSUE THREAD

**Issue by rishson** [dojo/meta#95]
Epic to track what work we can do to help users create well behaved and performant web apps.

Initial focus:

any build time optimisations we can do (compress, minify etc)?
any architectural patterns we can promote through `app`?

**Comment by kitsonk** [comment]
CLI Build already minifies and does dead code removal when building for production.  The static build flag feature will provide further ability to do optimisation.  That sort of resolves the first bullet point.

The second bullet point is under consideration.

**Comment by kitsonk** [comment]
At the moment this is largely un-actionable.  We continue to keep an eye on performance, and individual issues can be addressed as we go along, but closing for the ability to keep focused on actionable items.
