### ISSUE TITLE
Add license tree info to README

### ISSUE THREAD

**Issue by rishson** [dojo/meta#98]
We should list all the dependencies that a user will need use in a Dojo 2 app, e.g. Marquette, rxJs, immutable...
Alongside the dep we should also state the dep's licensing model, like you see when you run a repo through [librariesio](https://libraries.io), as can be seen in [this](https://libraries.io/npm/dojo2-todo-mvc) review to `todo-mvc`.

**Comment by agubler** [comment]
we unpublished that, surprised it still shows on libraries.io

**Comment by rishson** [comment]
Waking this issue up, to link all dojo packages to DependencyCI and publish links in meta.

**Comment by kitsonk** [comment]
License auditing has been implemented by JS Foundation.  In my opinion that meets the need of this issue.  What other actions should we take if any?

**Comment by kitsonk** [comment]
Closing for now until we identify other actions.
